import {gameState,bindTheme} from './state.js';
const $=id=>document.getElementById(id);
bindTheme($('games-theme'));
const allowed=['all','multiplayer','single','pinned'];
function current(){const value=new URL(location.href).searchParams.get('mode');return allowed.includes(value)?value:'all';}
function render(){const state=gameState.library(),filter=current(),show=filter!=='multiplayer'&&(filter!=='pinned'||state.pinned);$('games-pin').setAttribute('aria-pressed',String(state.pinned));$('games-pin').textContent=state.pinned?'Unpin FRACTURE':'Pin FRACTURE';document.querySelectorAll('[data-game-filter]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.gameFilter===filter)));$('games-result').hidden=!show;$('games-no-results').hidden=show;$('games-count').textContent=show?'1 game':'0 games';$('games-empty-title').textContent=filter==='multiplayer'?'Online battles are still in development':'No pinned games yet';$('games-empty-copy').textContent=filter==='multiplayer'?'FRACTURE has single-player training now. Public matchmaking and private rooms will appear here when they’re connected to a real server.':'Pin FRACTURE from its featured card to keep it here.';$('games-recent-empty').hidden=!!state.recent;$('games-recent').hidden=!state.recent;$('games-recent').replaceChildren();if(state.recent){const li=document.createElement('li'),a=document.createElement('a'),time=document.createElement('time');a.href=gameState.link('fracture/');a.textContent='FRACTURE · Continue training';time.dateTime=new Date(state.recent).toISOString();time.textContent=new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(state.recent);a.append(time);li.append(a);$('games-recent').append(li);}$('games-storage-status').textContent=gameState.available()?'Pins and recently played stay on this device, separately from revision progress.':'Browser storage is unavailable. Your pin applies for this visit, but may not survive closing.';}
function filter(value){const url=new URL(location.href);if(value==='all')url.searchParams.delete('mode');else url.searchParams.set('mode',value);history.pushState(null,'',url);render();}
document.querySelectorAll('[data-game-filter]').forEach(button=>button.addEventListener('click',()=>filter(button.dataset.gameFilter)));
$('games-show-all').addEventListener('click',()=>filter('all'));
$('games-pin').addEventListener('click',()=>{gameState.pin(!gameState.library().pinned);render();});
window.addEventListener('popstate',render);
render();
