window.FLASHCARD_DATA = {
  subjects: [
    {
      id: "english",
      name: "AQA English Literature",
      decks: [
        {
          id: "macbeth",
          title: "Macbeth",
          description: "Key quotations, characters, themes and exam-ready analysis for the November mock.",
          priority: true,
          cards: [
            { id: "mac-01", question: "How does Shakespeare first present Macbeth before he appears on stage?", quote: "‘brave Macbeth — well he deserves that name’", answer: "The Captain’s praise establishes Macbeth as a heroic warrior. The adjective ‘brave’ makes his later tyranny feel like a tragic fall, while the aside-like dash stresses that the title is earned through loyal service.", exam: "Use this as the start of a character arc: honoured soldier → regicide → isolated tyrant.", tags: ["Macbeth", "ambition", "tragic hero"] },
            { id: "mac-02", question: "Which quotation captures Macbeth’s hidden ambition in Act 1?", quote: "‘Stars, hide your fires; / Let not light see my black and deep desires’", answer: "The imperatives personify the stars as witnesses Macbeth wants to silence. Light and darkness imagery shows he already recognises the moral evil of his desires, so ambition is presented as conscious and secretive.", exam: "Link darkness to secrecy, evil and the disruption of God’s order.", tags: ["Macbeth", "ambition", "light and dark"] },
            { id: "mac-03", question: "How does Macbeth describe his only motive for killing Duncan?", quote: "‘I have no spur … but only / Vaulting ambition’", answer: "The extended horse-riding metaphor suggests ambition leaps beyond safe limits and will ‘o’erleap’ itself. Macbeth understands that ambition without moral restraint causes its own collapse.", exam: "A strong thesis quotation: Shakespeare presents unchecked ambition as self-destructive.", tags: ["Macbeth", "ambition", "metaphor"] },
            { id: "mac-04", question: "What does Lady Macbeth ask the spirits to do, and why is it significant?", quote: "‘unsex me here’", answer: "The imperative rejects Jacobean expectations of feminine softness so she can pursue violence. It also makes her willingness to invite supernatural influence seem transgressive to a contemporary audience.", exam: "Discuss gender expectations carefully: she associates masculinity with cruelty, but the play later challenges that idea.", tags: ["Lady Macbeth", "gender", "supernatural"] },
            { id: "mac-05", question: "How does Lady Macbeth use maternal imagery to prove her ruthlessness?", quote: "‘dash’d the brains out, had I so sworn as you’", answer: "The shocking image corrupts motherhood, which Jacobean society associated with nurture. Her hyperbole manipulates Macbeth by contrasting her imagined resolve with his hesitation.", exam: "Pair with her later vulnerability: ‘All the perfumes of Arabia…’.", tags: ["Lady Macbeth", "gender", "violence"] },
            { id: "mac-06", question: "Which image does Lady Macbeth use to teach Macbeth deception?", quote: "‘look like th’ innocent flower, / But be the serpent under’t’", answer: "The contrast between flower and serpent creates a deceptive appearance/reality image. The serpent alludes to Satan in Genesis, associating the murder plot with temptation and the destruction of innocence.", exam: "Link to the witches’ ‘fair is foul’ and the play’s repeated distrust of appearances.", tags: ["Lady Macbeth", "appearance", "religion"] },
            { id: "mac-07", question: "How does Duncan’s language create dramatic irony at Inverness?", quote: "‘This castle hath a pleasant seat’", answer: "Duncan’s positive adjective shows his trusting nature just as the audience knows he is entering danger. The dramatic irony makes Macbeth’s hospitality a profound betrayal of king, guest and kinsman.", exam: "Use for kingship, deception, or the violation of hospitality.", tags: ["Duncan", "dramatic irony", "kingship"] },
            { id: "mac-08", question: "What hallucination leads Macbeth towards Duncan’s murder?", quote: "‘Is this a dagger which I see before me’", answer: "The interrogative and hallucinated dagger externalise Macbeth’s divided mind. It could be supernatural temptation or a projection of his ‘heat-oppressed brain’, keeping responsibility ambiguous but not removing his choice.", exam: "Analyse the soliloquy as private conflict: Macbeth understands the horror yet continues.", tags: ["Macbeth", "guilt", "supernatural"] },
            { id: "mac-09", question: "How does Macbeth react immediately after killing Duncan?", quote: "‘Macbeth does murder sleep’", answer: "Sleep symbolises innocence, peace and natural order. By personifying himself as sleep’s murderer, Macbeth recognises that regicide has destroyed his own chance of rest.", exam: "Track sleep imagery through Lady Macbeth’s sleepwalking and Macbeth’s mental punishment.", tags: ["Macbeth", "guilt", "sleep"] },
            { id: "mac-10", question: "Which image shows Macbeth believes his guilt is permanent?", quote: "‘Will all great Neptune’s ocean wash this blood / Clean from my hand?’", answer: "The rhetorical question and mythological hyperbole make his guilt immeasurable. Blood is both physical evidence and a symbol of moral responsibility that cannot simply be washed away.", exam: "Contrast with Lady Macbeth’s early claim: ‘A little water clears us of this deed.’", tags: ["Macbeth", "guilt", "blood"] },
            { id: "mac-11", question: "How does Lady Macbeth initially dismiss guilt after Duncan’s murder?", quote: "‘A little water clears us of this deed’", answer: "The adjective ‘little’ and simple declarative minimise the crime, showing her early confidence that guilt can be controlled. Her later obsessive hand-washing exposes this belief as tragically false.", exam: "Pair with ‘Out, damned spot!’ to show structural change.", tags: ["Lady Macbeth", "guilt", "change"] },
            { id: "mac-12", question: "How does Banquo warn Macbeth about the witches?", quote: "‘the instruments of darkness tell us truths’", answer: "The metaphor presents the witches as tools of evil. Banquo understands that truthful predictions may be bait leading to ‘deepest consequence’, making his restraint a moral contrast to Macbeth.", exam: "Useful for free will: both hear prophecy, but only Macbeth chooses murder.", tags: ["Banquo", "supernatural", "free will"] },
            { id: "mac-13", question: "What paradox establishes the witches’ influence over the play?", quote: "‘Fair is foul, and foul is fair’", answer: "The balanced paradox collapses the difference between good and evil, creating a world of moral confusion. Its echo in Macbeth’s first line links him to the witches before they meet.", exam: "Use for appearance versus reality or the supernatural atmosphere.", tags: ["witches", "appearance", "structure"] },
            { id: "mac-14", question: "How do the witches appeal to Macbeth’s ambition in their greeting?", quote: "‘All hail, Macbeth, that shalt be king hereafter!’", answer: "The ceremonial repetition of ‘hail’ gives the prophecy authority, while the future certainty of ‘shalt’ invites Macbeth to imagine kingship as inevitable. Shakespeare leaves open whether prophecy causes or merely awakens ambition.", exam: "Avoid saying the witches control Macbeth; stress temptation and choice.", tags: ["witches", "ambition", "fate"] },
            { id: "mac-15", question: "How does Macbeth admit his fear of Banquo?", quote: "‘Our fears in Banquo stick deep’", answer: "The first-person plural may imitate royal speech, but ‘stick deep’ suggests a private wound or embedded weapon. Banquo’s ‘royalty of nature’ threatens Macbeth because legitimate nobility cannot be manufactured by a crown.", exam: "Use to explain why ambition becomes paranoid tyranny.", tags: ["Macbeth", "Banquo", "fear"] },
            { id: "mac-16", question: "What does Macbeth’s plan for Banquo show about his development?", quote: "‘Be innocent of the knowledge, dearest chuck’", answer: "Macbeth now excludes Lady Macbeth from murder plans, reversing their earlier dynamic. The patronising endearment and dramatic irony show that he has absorbed her lesson in deception and acts independently.", exam: "This is a useful midpoint quotation for changing power within the marriage.", tags: ["Macbeth", "Lady Macbeth", "power"] },
            { id: "mac-17", question: "How does Macbeth describe his mental state after becoming king?", quote: "‘O, full of scorpions is my mind, dear wife!’", answer: "The violent metaphor makes his thoughts poisonous, restless and self-attacking. Kingship gained through violence gives him fear rather than security.", exam: "Connect internal torment to the play’s argument that immoral power cannot bring peace.", tags: ["Macbeth", "guilt", "kingship"] },
            { id: "mac-18", question: "How does Banquo’s ghost reveal Macbeth’s guilt?", quote: "‘Thou canst not say I did it: never shake / Thy gory locks at me’", answer: "Macbeth’s denial paradoxically reveals his responsibility. ‘Gory’ makes the hidden violence visible at a public feast, so his private guilt begins to destroy his authority.", exam: "Discuss the ghost as supernatural reality or psychological projection; either reading exposes guilt.", tags: ["Macbeth", "Banquo", "guilt"] },
            { id: "mac-19", question: "Which quotation shows Macbeth committing himself to further violence?", quote: "‘I am in blood / Stepp’d in so far’", answer: "The extended river-of-blood metaphor suggests he feels surrounded by the consequences of murder. He treats continued violence as easier than repentance, but Shakespeare makes clear this is a chosen rationalisation.", exam: "Excellent for the turning point from hesitant murderer to deliberate tyrant.", tags: ["Macbeth", "violence", "choice"] },
            { id: "mac-20", question: "How does Lady Macbeth’s sleepwalking language show psychological collapse?", quote: "‘Out, damned spot! out, I say!’", answer: "The repeated imperative echoes her former authority, but it is now powerless against an imagined bloodstain. ‘Damned’ suggests both guilt and fear of eternal punishment.", exam: "Contrast prose-like fragmentation here with her controlled blank verse earlier.", tags: ["Lady Macbeth", "guilt", "religion"] },
            { id: "mac-21", question: "How does Lady Macbeth show that guilt has become infinite?", quote: "‘All the perfumes of Arabia will not sweeten this little hand’", answer: "The hyperbolic ‘all’ contrasts with ‘little’, showing that a seemingly small hand carries enormous guilt. Sweet perfume cannot mask the moral ‘smell’ of blood, reversing her earlier confidence about water.", exam: "Use sensory imagery: imagined sight, smell and touch make guilt inescapable.", tags: ["Lady Macbeth", "guilt", "imagery"] },
            { id: "mac-22", question: "How does Macbeth respond to Lady Macbeth’s death?", quote: "‘Tomorrow, and tomorrow, and tomorrow’", answer: "The monotonous repetition slows time and conveys numbness. Macbeth sees life as repetitive and empty, the opposite of the meaningful future promised by his ambition.", exam: "Link the soliloquy to nihilism: gaining power has stripped life of value.", tags: ["Macbeth", "death", "time"] },
            { id: "mac-23", question: "What metaphor expresses Macbeth’s final view of life?", quote: "‘Life’s but a walking shadow’", answer: "A shadow is insubstantial and temporary, suggesting Macbeth now sees existence as meaningless. The theatrical images that follow—‘poor player’ and ‘tale’—make human ambition appear brief and futile.", exam: "Use as the endpoint of his tragic arc: promised greatness ends in emptiness.", tags: ["Macbeth", "death", "tragic hero"] },
            { id: "mac-24", question: "How does Malcolm define a good king?", quote: "‘justice, verity, temp’rance, stableness’", answer: "The list of moral ‘king-becoming graces’ presents legitimate rule as truthful, restrained and stable. Each quality contrasts with Macbeth’s injustice, deception, excess and insecurity.", exam: "Use Malcolm as a foil when answering on kingship or leadership.", tags: ["Malcolm", "kingship", "foil"] },
            { id: "mac-25", question: "How does Macduff challenge Macbeth’s idea of masculinity?", quote: "‘I must also feel it as a man’", answer: "Macduff rejects the idea that manhood means suppressing emotion. ‘Also’ allows both grief and action, offering a balanced masculinity based on love, justice and courage.", exam: "Contrast with Lady Macbeth’s taunts and Macbeth’s violent proof of manhood.", tags: ["Macduff", "masculinity", "family"] },
            { id: "mac-26", question: "What does Macduff reveal about Macbeth’s trust in the apparitions?", quote: "‘Macduff was from his mother’s womb / Untimely ripp’d’", answer: "The revelation exploits the witches’ equivocation: Macduff was not born in the ordinary sense. Violent birth imagery overturns Macbeth’s false security and shows the danger of hearing only what ambition wants to hear.", exam: "Use for equivocation, fate and Macbeth’s flawed interpretation.", tags: ["Macduff", "witches", "equivocation"] },
            { id: "mac-27", question: "How is Scotland personified under Macbeth’s rule?", quote: "‘Bleed, bleed, poor country!’", answer: "Macduff personifies Scotland as a wounded body. Repetition intensifies the suffering and shows that tyranny harms an entire nation, not only the ruler’s private enemies.", exam: "Connect Macbeth’s moral disorder with political and natural disorder.", tags: ["Scotland", "tyranny", "violence"] },
            { id: "mac-28", question: "How does the ending restore legitimate order?", quote: "‘Hail, King of Scotland!’", answer: "The collective acclamation of Malcolm echoes the witches’ earlier ‘hail’ to Macbeth but replaces deceptive prophecy with public legitimacy. The circular echo helps close the period of disorder.", exam: "End an essay on kingship by showing order restored, while remembering the play’s heavy cost.", tags: ["Malcolm", "kingship", "structure"] }
          ]
        },
        { id: "christmas-carol", title: "A Christmas Carol", description: "Core quotations and analysis on Scrooge’s transformation, poverty, family and social responsibility.", priority: true, cards: [
          { id: "acc-01", question: "How is Scrooge presented at the start of the novella?", quote: "‘a squeezing, wrenching, grasping, scraping, clutching, covetous old sinner!’", answer: "The cumulative list of violent present participles makes greed seem active and relentless. ‘Sinner’ frames his selfishness as a moral failing, while the narrator’s energetic voice makes the criticism memorable.", exam: "Use this as the starting point of Scrooge’s transformation.", tags: ["Scrooge", "greed", "characterisation"] },
          { id: "acc-02", question: "Which simile captures Scrooge’s emotional isolation?", quote: "‘solitary as an oyster’", answer: "An oyster is closed, hard and isolated, reflecting Scrooge’s self-protection. Yet it may contain a pearl, quietly foreshadowing the value and generosity that can be recovered from within him.", exam: "The simile supports both his isolation and the possibility of redemption.", tags: ["Scrooge", "isolation", "redemption"] },
          { id: "acc-03", question: "How does Dickens use weather imagery to describe Scrooge?", quote: "‘No warmth could warm, no wintry weather chill him’", answer: "The parallel negatives make Scrooge seem more powerful than the weather because his coldness comes from within. Pathetic fallacy is reversed: he affects the atmosphere around him.", exam: "Track the movement from cold and darkness to warmth and light.", tags: ["Scrooge", "cold", "imagery"] },
          { id: "acc-04", question: "How does Scrooge respond to charity collectors?", quote: "‘Are there no prisons? … And the Union workhouses?’", answer: "The rhetorical questions echo harsh Victorian attitudes that blamed the poor. Dickens makes Scrooge speak the language of institutions so readers can see how systems replace human compassion.", exam: "Connect to the 1834 Poor Law and Dickens’s criticism of punitive welfare.", tags: ["Scrooge", "poverty", "context"] },
          { id: "acc-05", question: "Which brutal phrase reveals Scrooge’s Malthusian attitude?", quote: "‘decrease the surplus population’", answer: "The economic noun ‘surplus’ dehumanises poor people as excess numbers. Dickens later returns Scrooge’s own words to him, forcing both character and reader to recognise their cruelty.", exam: "Link context to argument, not as a bolt-on: Dickens attacks language that erases individual lives.", tags: ["Scrooge", "poverty", "social responsibility"] },
          { id: "acc-06", question: "How does Fred define Christmas?", quote: "‘a kind, forgiving, charitable, pleasant time’", answer: "The warm list turns Christmas into a set of social values rather than merely a religious date. Fred acts as Scrooge’s foil because he values relationships despite having little money.", exam: "Use Fred to express Dickens’s moral message about generosity and community.", tags: ["Fred", "Christmas", "foil"] },
          { id: "acc-07", question: "How does Marley explain the duty he neglected?", quote: "‘Mankind was my business’", answer: "The business metaphor corrects Marley’s obsession with profit: a person’s true work is care for others. The simple declarative gives Dickens’s social message the force of a moral lesson.", exam: "This can anchor an essay on responsibility across the whole novella.", tags: ["Marley", "responsibility", "message"] },
          { id: "acc-08", question: "What does Marley’s chain symbolise?", quote: "‘I wear the chain I forged in life’", answer: "The first-person verbs stress that Marley created his own punishment through repeated selfish choices. Its cashboxes and ledgers make material greed a literal spiritual burden.", exam: "Link consequences to free will: the chain is self-forged, so Scrooge can still choose differently.", tags: ["Marley", "greed", "symbolism"] },
          { id: "acc-09", question: "How is Scrooge’s childhood isolation presented?", quote: "‘a solitary child, neglected by his friends’", answer: "The passive ‘neglected’ invites sympathy and helps explain, without excusing, his adult isolation. Dickens suggests memory and empathy can reconnect a hardened adult with vulnerable childhood feelings.", exam: "Show complexity: Scrooge is responsible for change, but his past helps readers understand him.", tags: ["Scrooge", "childhood", "isolation"] },
          { id: "acc-10", question: "How does Fan’s memory complicate Scrooge’s character?", quote: "‘Home, for good and all. Home, for ever and ever.’", answer: "The repetition and exclamatory warmth contrast with Scrooge’s lonely school. Fan represents unconditional family love, and her connection to Fred makes Scrooge’s rejection of his nephew more painful.", exam: "Use to link memory, family and the gradual revival of emotion.", tags: ["Fan", "family", "memory"] },
          { id: "acc-11", question: "How is Fezziwig presented as a good employer?", quote: "‘the happiness he gives, is quite as great as if it cost a fortune’", answer: "Scrooge recognises that Fezziwig’s moral influence matters more than money. The comparison challenges employers to use small acts of respect and generosity to transform workers’ lives.", exam: "Contrast Fezziwig’s warm workplace with Scrooge’s cold counting-house.", tags: ["Fezziwig", "work", "generosity"] },
          { id: "acc-12", question: "Why does Belle end her engagement to Scrooge?", quote: "‘Another idol has displaced me … a golden one’", answer: "The religious metaphor presents money as a false god. ‘Golden’ sounds attractive but exposes how worship of wealth has displaced love and corrupted Scrooge’s priorities.", exam: "Use for greed, religion or the personal cost of materialism.", tags: ["Belle", "greed", "religion"] },
          { id: "acc-13", question: "How is the Ghost of Christmas Present first presented?", quote: "‘a jolly Giant, glorious to see’", answer: "The exuberant adjectives and capitalised ‘Giant’ create abundance and warmth. The spirit’s open manner contrasts with Scrooge’s closed body and home, embodying generous Christmas fellowship.", exam: "Analyse contrast in colour, light, food and physical openness.", tags: ["Ghost of Christmas Present", "abundance", "Christmas"] },
          { id: "acc-14", question: "How does Dickens present the Cratchits’ Christmas dinner?", quote: "‘There never was such a goose’", answer: "The narrator adopts the family’s excited perspective, using comic exaggeration to turn a modest meal into a feast. Their gratitude and affection expose the poverty of Scrooge’s wealthy but lonely life.", exam: "Avoid calling the family simply happy: Dickens celebrates love while still exposing hardship.", tags: ["Cratchits", "family", "poverty"] },
          { id: "acc-15", question: "Which statement captures the Cratchits’ unity?", quote: "‘They were not a handsome family … but they were happy, grateful, pleased with one another’", answer: "The adversative ‘but’ rejects superficial judgments based on appearance or wealth. The triplet locates real richness in mutual love and gratitude.", exam: "Use as a direct contrast with Scrooge’s material wealth and emotional poverty.", tags: ["Cratchits", "family", "wealth"] },
          { id: "acc-16", question: "How is Tiny Tim used to challenge social indifference?", quote: "‘If these shadows remain unaltered by the Future, the child will die’", answer: "The conditional warning makes Tim’s death preventable rather than inevitable. Dickens turns social responsibility into a question of choices made now, while echoing Scrooge’s own language back at him.", exam: "Tim is both an individual child and a symbol of vulnerable people harmed by neglect.", tags: ["Tiny Tim", "poverty", "responsibility"] },
          { id: "acc-17", question: "What does Tiny Tim hope churchgoers remember?", quote: "‘who made lame beggars walk, and blind men see’", answer: "The biblical allusion connects disability and poverty with Christ’s compassion, not blame. Tim’s concern for others despite his own suffering gives him moral authority.", exam: "Link Christian responsibility to the novella’s call for active kindness.", tags: ["Tiny Tim", "religion", "compassion"] },
          { id: "acc-18", question: "What do Ignorance and Want represent?", quote: "‘This boy is Ignorance. This girl is Want. Beware them both’", answer: "The allegorical children make abstract social problems visible and vulnerable. The imperative ‘Beware’ warns that denying education and basic needs will harm all of society.", exam: "Mention that Dickens directs responsibility outward: these children cling to society’s spirit.", tags: ["Ignorance and Want", "poverty", "allegory"] },
          { id: "acc-19", question: "How does the Ghost of Christmas Yet to Come communicate?", quote: "‘The Phantom slowly, gravely, silently approached’", answer: "The triple adverbs create solemn fear, and its silence forces Scrooge to interpret the future himself. Unlike a fixed prophecy, the visions motivate him to choose change.", exam: "Use the spirit’s ambiguity for fear, death, or free will.", tags: ["Ghost of Christmas Yet to Come", "fear", "structure"] },
          { id: "acc-20", question: "How do the businessmen react to Scrooge’s death?", quote: "‘I don’t mind going if a lunch is provided’", answer: "The conditional joke shows that Scrooge’s death matters only if it offers material benefit. Dickens uses dark comedy to show the empty social legacy created by a life without generosity.", exam: "Contrast this response with the genuine grief surrounding Tiny Tim.", tags: ["Scrooge", "death", "isolation"] },
          { id: "acc-21", question: "How does Scrooge show that the future can change?", quote: "‘I will honour Christmas in my heart, and try to keep it all the year’", answer: "The modal ‘will’ signals determination, while ‘all the year’ expands Christmas charity into a permanent way of living. ‘Heart’ suggests his transformation is emotional and moral, not performative.", exam: "Use for redemption and Dickens’s broader definition of Christmas spirit.", tags: ["Scrooge", "redemption", "Christmas"] },
          { id: "acc-22", question: "What shows Scrooge’s joyful rebirth on Christmas morning?", quote: "‘I am as light as a feather, I am as happy as an angel’", answer: "The repeated similes and anaphora create breathless delight. ‘Light’ reverses the heavy chain and cold imagery, while ‘angel’ suggests spiritual renewal.", exam: "Analyse Dickens’s change in semantic field from weight, darkness and cold to light and warmth.", tags: ["Scrooge", "redemption", "imagery"] },
          { id: "acc-23", question: "How does Scrooge make amends to Bob?", quote: "‘I’ll raise your salary, and endeavour to assist your struggling family’", answer: "Concrete future verbs turn regret into practical responsibility. ‘Endeavour’ implies continuing effort: redemption requires sustained action, not a single emotional moment.", exam: "Use to show that Dickens links moral change with material help for the poor.", tags: ["Scrooge", "Bob Cratchit", "responsibility"] },
          { id: "acc-24", question: "How does the narrator summarise Scrooge’s transformation?", quote: "‘as good a friend, as good a master, and as good a man’", answer: "The parallel triplet measures change through relationships: social, economic and personal. Repetition of ‘good’ gives the ending the direct clarity of a moral fable.", exam: "A strong concluding quotation for almost any Scrooge essay.", tags: ["Scrooge", "redemption", "ending"] },
          { id: "acc-25", question: "Why is the final Tiny Tim line structurally important?", quote: "‘God bless Us, Every One!’", answer: "The inclusive pronouns extend the blessing beyond one family to society as a whole. Ending on Tim’s voice combines Christian compassion, social unity and hope.", exam: "Use to conclude on Dickens’s inclusive message: nobody should be treated as ‘surplus’.", tags: ["Tiny Tim", "ending", "community"] },
          { id: "acc-26", question: "How does Dickens establish social contrast on Christmas Eve?", quote: "‘The fog came pouring in at every chink and keyhole’", answer: "The invasive fog reflects moral blindness and a city where social problems cannot be shut out. It surrounds rich and poor alike, suggesting shared social conditions and responsibilities.", exam: "Link setting to the novella’s movement from obscurity and isolation towards light and connection.", tags: ["setting", "fog", "social responsibility"] }
        ] },
        { id: "inspector-calls", title: "An Inspector Calls", description: "Character, theme and structure revision for Priestley’s morality play.", cards: [
          { id: "aic-01", question: "How do the opening stage directions present the Birlings’ home?", quote: "‘substantial and heavily comfortable, but not cosy and homelike’", answer: "The contrast reveals material wealth without emotional warmth. ‘Heavily’ makes comfort seem oppressive, preparing the audience to question the family’s values.", exam: "Stage directions are deliberate evidence: use them as closely as dialogue.", tags: ["setting", "class", "family"] },
          { id: "aic-02", question: "How does Mr Birling express capitalist individualism?", quote: "‘a man has to mind his own business and look after himself’", answer: "The repeated reflexive idea makes responsibility narrowly individual. Priestley gives Birling this view just before the Inspector arrives to challenge it.", exam: "Contrast directly with the Inspector’s collective ‘we’ language.", tags: ["Mr Birling", "capitalism", "responsibility"] },
          { id: "aic-03", question: "How does dramatic irony undermine Mr Birling’s authority?", quote: "‘unsinkable, absolutely unsinkable’", answer: "A 1945 audience knows the Titanic sank, so the repeated certainty makes Birling foolish. Priestley encourages the audience to distrust his confident predictions and political views.", exam: "Connect dramatic irony to Priestley’s criticism of complacent capitalist authority.", tags: ["Mr Birling", "dramatic irony", "structure"] },
          { id: "aic-04", question: "What does Birling’s title reveal about his priorities?", quote: "‘there’s a fair chance that I might find my way into the next Honours List’", answer: "His hopeful language shows social ambition and insecurity. The possibility of a knighthood matters more to him than justice, which explains his panic about scandal.", exam: "Link status anxiety to how Birling treats workers and the Inspector.", tags: ["Mr Birling", "class", "reputation"] },
          { id: "aic-05", question: "How does Sheila initially reveal privilege?", quote: "‘these girls aren’t cheap labour — they’re people’", answer: "The dash corrects capitalist language by restoring the workers’ humanity. Although ‘these girls’ still sounds distanced, Sheila begins to learn quickly and voices Priestley’s hope for change.", exam: "Track her movement from consumer power to empathy and responsibility.", tags: ["Sheila", "class", "change"] },
          { id: "aic-06", question: "How does Sheila respond to her part in Eva’s dismissal?", quote: "‘I know I’m to blame — and I’m desperately sorry’", answer: "The direct admission contrasts with her parents’ evasions. ‘Desperately’ conveys genuine emotion, while the dash moves from responsibility to remorse.", exam: "Use Sheila as evidence that accepting guilt is the first step toward social change.", tags: ["Sheila", "guilt", "responsibility"] },
          { id: "aic-07", question: "How does Mrs Birling distance herself from working-class women?", quote: "‘Girls of that class—’", answer: "The dismissive noun phrase reduces individuals to a social category. The broken-off line suggests entrenched prejudice so obvious to her that it needs no explanation.", exam: "Link class prejudice to her failure in a charitable role.", tags: ["Mrs Birling", "class", "prejudice"] },
          { id: "aic-08", question: "How does Mrs Birling use her power against Eva?", quote: "‘I used my influence to have it refused’", answer: "The active verb ‘used’ makes her responsibility unmistakable, despite her later denials. Priestley exposes the hypocrisy of charity controlled by class prejudice.", exam: "Compare institutional respectability with the harm it can hide.", tags: ["Mrs Birling", "power", "hypocrisy"] },
          { id: "aic-09", question: "How does Eric describe Eva’s treatment by the family?", quote: "‘we all helped to kill her’", answer: "The inclusive pronoun accepts collective responsibility and ‘kill’ removes comfortable euphemism. Eric understands that separate acts of exploitation combine into fatal harm.", exam: "Use as a concise summary of the play’s chain-of-events structure.", tags: ["Eric", "responsibility", "family"] },
          { id: "aic-10", question: "What does Eric’s account reveal about gender and power?", quote: "‘I was in that state when a chap easily turns nasty’", answer: "The euphemistic ‘that state’ evades full detail, while ‘easily’ exposes how male entitlement and alcohol enable violence. His admission is disturbing even though he later accepts responsibility.", exam: "Do not excuse Eric; analyse both his exploitation and his capacity to change.", tags: ["Eric", "gender", "power"] },
          { id: "aic-11", question: "How does Gerald frame his relationship with Daisy Renton?", quote: "‘I didn’t feel about her as she felt about me’", answer: "The unequal parallel structure acknowledges an emotional imbalance. His honesty is limited because he still controlled the money, housing and ending of the relationship.", exam: "Discuss Gerald as complex: capable of kindness, but protected by class and gender power.", tags: ["Gerald", "Eva Smith", "power"] },
          { id: "aic-12", question: "How does the Inspector state Priestley’s central message?", quote: "‘We are members of one body. We are responsible for each other.’", answer: "The body metaphor presents society as interdependent: harm to one part affects the whole. Short declaratives and inclusive pronouns give the message moral certainty.", exam: "Anchor a responsibility essay here, then show how each character accepts or rejects it.", tags: ["Inspector", "socialism", "responsibility"] },
          { id: "aic-13", question: "What warning does the Inspector give at the end of his speech?", quote: "‘fire and blood and anguish’", answer: "The violent triplet sounds biblical and may allude to the two world wars the 1945 audience has experienced. Priestley warns that ignoring inequality brings collective suffering.", exam: "Connect the 1912 setting to the 1945 audience without treating context as separate.", tags: ["Inspector", "warning", "context"] },
          { id: "aic-14", question: "How does Sheila understand the Inspector’s purpose?", quote: "‘He’s giving us the rope — so that we’ll hang ourselves’", answer: "The metaphor shows the Inspector lets characters expose themselves through their own words. Sheila’s perceptiveness separates her from the older generation and aligns her with the audience.", exam: "Useful for the Inspector’s methods and Sheila’s development.", tags: ["Sheila", "Inspector", "dramatic method"] },
          { id: "aic-15", question: "How does Mr Birling react when he thinks the danger has passed?", quote: "‘The famous younger generation who know it all. And they can’t even take a joke.’", answer: "His sarcasm trivialises Eva’s death and shows he has learnt nothing. The phrase ‘younger generation’ also highlights Priestley’s structural divide between hope and resistance.", exam: "Compare with Sheila and Eric, who insist the moral truth matters even if the Inspector was not real.", tags: ["Mr Birling", "generations", "ending"] },
          { id: "aic-16", question: "How does Sheila reject Gerald at the end?", quote: "‘You and I aren’t the same people who sat down to dinner here’", answer: "The dinner becomes a structural marker dividing ignorance from knowledge. Sheila understands that genuine learning changes identity, while Gerald tries to restore the old order.", exam: "Use for change, relationships, or the cyclical structure.", tags: ["Sheila", "Gerald", "change"] },
          { id: "aic-17", question: "Why is Eva Smith’s name significant?", quote: "‘Eva Smith’", answer: "‘Eva’ recalls Eve, suggesting a foundational or representative woman, while ‘Smith’ is a very common surname. She can therefore stand for countless exploited working-class people while remaining the play’s absent moral centre.", exam: "Avoid claiming she is literally multiple people; say Priestley deliberately makes her representative.", tags: ["Eva Smith", "symbolism", "class"] },
          { id: "aic-18", question: "How does the final phone call shape the play?", quote: "‘A girl has just died … after swallowing some disinfectant’", answer: "The call repeats the original crisis and creates a cyclical ending. Just as the family dismisses the evening as a hoax, consequence returns, confirming that the moral lesson matters beyond the Inspector’s identity.", exam: "Use the ending to show urgency: society must learn, or repeat its mistakes.", tags: ["ending", "structure", "responsibility"] },
          { id: "aic-19", question: "How is the Inspector’s arrival timed for dramatic effect?", quote: "‘We hear the sharp ring of the front door bell’", answer: "The adjective ‘sharp’ cuts through Birling’s individualist speech at the exact moment he dismisses collective responsibility. The interruption makes the Inspector a structural challenge to Birling’s ideology.", exam: "Comment on timing and stagecraft, not only dialogue.", tags: ["Inspector", "structure", "stagecraft"] },
          { id: "aic-20", question: "How do the stage directions change when the Inspector arrives?", quote: "‘the lighting should be pink and intimate until the INSPECTOR arrives, and then it should be brighter and harder’", answer: "The exposing light replaces flattering comfort with moral scrutiny. ‘Harder’ suggests uncomfortable truth, turning the stage itself into a visual symbol of interrogation.", exam: "An excellent opening paragraph for essays on the Inspector or appearance and reality.", tags: ["Inspector", "lighting", "stagecraft"] }
        ] }
      ]
    },
    { id: "history", name: "Edexcel History", decks: [
      { id: "cold-war", title: "The Cold War", description: "A starter structure for superpower relations. Match dates and depth to your school organiser when available.", cards: [
        { id: "cw-01", question: "What was the central ideological divide after the Second World War?", quote: "Capitalism versus communism", answer: "The USA promoted private ownership and multi-party democracy, while the USSR used state ownership and one-party rule. Security fears and incompatible systems deepened distrust between former allies.", exam: "Frame causes as linked: ideology, security, leadership and specific flashpoints.", tags: ["ideology", "USA", "USSR"] },
        { id: "cw-02", question: "Why was the Truman Doctrine announced in 1947?", quote: "Containment", answer: "Truman pledged support for peoples resisting communist pressure, initially focused on Greece and Turkey. It turned containment into an explicit US policy and sharpened the division of Europe.", exam: "Link to the Marshall Plan: political commitment was followed by economic support.", tags: ["Truman Doctrine", "containment", "1947"] },
        { id: "cw-03", question: "What was the purpose of the Marshall Plan?", quote: "European Recovery Program", answer: "US financial aid aimed to rebuild European economies, encourage trade and reduce the appeal of communism. Stalin viewed it as economic influence and prevented Eastern European states from joining.", exam: "Explain both US aims and Soviet interpretation.", tags: ["Marshall Plan", "economy", "1947"] },
        { id: "cw-04", question: "Why was the Berlin Blockade a major Cold War crisis?", quote: "June 1948–May 1949", answer: "Stalin blocked land access to West Berlin after Western currency reform. The Western Allies supplied the city by air, and the blockade ended without either side starting direct war.", exam: "Consequences include increased tension and the formation of West and East Germany in 1949.", tags: ["Berlin", "blockade", "airlift"] },
        { id: "cw-05", question: "What did the Cuban Missile Crisis reveal about Cold War danger?", quote: "Thirteen days, October 1962", answer: "Soviet nuclear missiles in Cuba triggered a US naval quarantine and brought the superpowers close to nuclear war. Compromise removed Soviet missiles from Cuba and secretly US missiles from Turkey.", exam: "Separate immediate resolution from longer-term consequences such as the hotline and Test Ban Treaty.", tags: ["Cuba", "nuclear", "1962"] },
        { id: "cw-06", question: "Why did the Berlin Wall fall in November 1989?", quote: "Reform, protest and a mistaken announcement", answer: "Gorbachev’s reforms weakened Soviet control, East German protests grew, and neighbouring borders opened. A confused travel announcement led crowds to checkpoints, where guards opened the crossings.", exam: "Avoid a single-cause answer: combine long-term Soviet change with immediate popular pressure.", tags: ["Berlin Wall", "Gorbachev", "1989"] }
      ] },
      { id: "henry-pending", title: "Henry unit", description: "Course title and content pending your school knowledge organiser. No specific Henry course has been assumed.", pending: true, cards: [] },
      { id: "medicine", title: "Medicine Through Time", description: "A starter framework for ideas, treatments, prevention and factors for change across the periods.", cards: [
        { id: "med-01", question: "What were the Four Humours?", quote: "Blood, phlegm, black bile and yellow bile", answer: "Hippocratic and Galenic medicine taught that illness resulted from an imbalance of four bodily fluids. Treatments such as bleeding and purging aimed to restore balance.", exam: "For significance, explain why the theory lasted: classical authority, church support and limited alternatives.", tags: ["medieval", "ideas", "Galen"] },
        { id: "med-02", question: "Why was Vesalius important to medical knowledge?", quote: "The Fabric of the Human Body, 1543", answer: "Careful human dissection allowed Vesalius to correct some of Galen’s anatomical errors. Printing spread detailed illustrations, although improved anatomy did not immediately create effective cures.", exam: "Separate knowledge of anatomy from progress in treatment.", tags: ["Renaissance", "Vesalius", "anatomy"] },
        { id: "med-03", question: "What did William Harvey demonstrate?", quote: "The circulation of the blood, 1628", answer: "Harvey used observation, dissection and calculation to show that the heart pumps blood around the body in a circuit. This challenged Galen, though capillaries could not yet be seen.", exam: "Use for the roles of individuals, experiment and changing attitudes.", tags: ["Harvey", "circulation", "Renaissance"] },
        { id: "med-04", question: "Why was Pasteur’s Germ Theory significant?", quote: "Microbes in the air cause decay, 1861", answer: "Pasteur provided scientific support for the idea that microorganisms cause decay, undermining spontaneous generation. Later researchers connected particular microbes to particular diseases.", exam: "Explain delayed impact: a theory needs application, communication and acceptance.", tags: ["Pasteur", "germs", "nineteenth century"] },
        { id: "med-05", question: "How did Fleming, Florey and Chain contribute to penicillin?", quote: "Discovery → development → mass production", answer: "Fleming observed penicillin’s antibacterial effect in 1928. Florey and Chain developed it into a usable drug, while wartime government and industry enabled mass production.", exam: "Ideal for a factors question: individuals, science, war, government and industry worked together.", tags: ["penicillin", "antibiotics", "factors"] },
        { id: "med-06", question: "What did the NHS change in 1948?", quote: "Healthcare free at the point of use", answer: "The National Health Service widened access to medical care regardless of ability to pay. It did not invent new treatments, but changed how widely existing services could be used.", exam: "Distinguish access and provision from scientific discovery.", tags: ["NHS", "government", "twentieth century"] }
      ] }
    ]},
    { id: "geography", name: "AQA Geography Paper 1", decks: [
      { id: "natural-hazards", title: "Natural Hazards", description: "Tectonic and weather hazards plus climate change; case studies can be adapted to your class choices.", cards: [
        { id: "geo-haz-01", question: "Why are tectonic hazards concentrated at plate margins?", quote: "Plate movement releases stored energy", answer: "Convection and slab processes move plates. Friction may lock margins until pressure is released as earthquakes; melting at some margins creates magma and volcanoes.", exam: "Name the margin and explain the sequence, rather than only stating that plates move.", tags: ["tectonics", "processes"] },
        { id: "geo-haz-02", question: "How do primary and secondary effects differ?", quote: "Direct impact versus later consequence", answer: "Primary effects result directly from the event, such as collapsed buildings. Secondary effects arise from primary impacts, such as fires, disease, landslides or homelessness.", exam: "Keep effects separate from responses in case-study answers.", tags: ["effects", "case studies"] },
        { id: "geo-haz-03", question: "What conditions allow a tropical storm to form?", quote: "Ocean water above about 27°C", answer: "Warm, deep ocean water fuels rising moist air and low pressure. Condensation releases energy; the Coriolis effect creates rotation away from the Equator, while low wind shear helps organisation.", exam: "Write it as a linked process chain.", tags: ["weather hazards", "tropical storms"] },
        { id: "geo-haz-04", question: "How can monitoring reduce hazard risk?", quote: "Prediction supports preparation", answer: "Satellite, seismic, gas and weather data can identify changes and improve warnings. Monitoring cannot prevent a natural event, but it can support evacuation and targeted emergency planning.", exam: "Evaluate limits: accuracy, cost, false alarms and access to communication.", tags: ["risk", "management"] },
        { id: "geo-haz-05", question: "What is the difference between climate mitigation and adaptation?", quote: "Reduce causes versus manage impacts", answer: "Mitigation lowers greenhouse-gas emissions or increases carbon storage. Adaptation changes places and behaviour to cope with effects, such as flood defences or drought-resistant crops.", exam: "Evaluation can compare timescale, cost and who benefits.", tags: ["climate change", "management"] }
      ] },
      { id: "living-world", title: "The Living World", description: "Ecosystems, tropical rainforests and option-ready structure for hot deserts or cold environments.", cards: [
        { id: "geo-live-01", question: "What links the parts of an ecosystem?", quote: "Flows of energy and nutrients", answer: "Producers capture energy, consumers transfer it through food chains, and decomposers recycle nutrients. Climate, soil, water, plants and animals are interdependent.", exam: "Use a named example to make interdependence concrete.", tags: ["ecosystems", "interdependence"] },
        { id: "geo-live-02", question: "Why are tropical rainforests highly biodiverse?", quote: "Year-round heat, water and sunlight", answer: "Constant high temperatures and rainfall support continuous plant growth. Layered vegetation creates many habitats and niches, while rapid nutrient cycling sustains productivity.", exam: "Link each climate feature to a biological consequence.", tags: ["rainforest", "biodiversity"] },
        { id: "geo-live-03", question: "Why can rainforest soils be infertile?", quote: "Rapid nutrient cycling and leaching", answer: "Most nutrients are stored in living biomass rather than soil. Heavy rain leaches minerals, and cleared land quickly loses fertility once the cycle is broken.", exam: "This explains why deforestation can cause long-term soil degradation.", tags: ["rainforest", "soils"] },
        { id: "geo-live-04", question: "What does sustainable ecosystem management aim to balance?", quote: "Environment, economy and people", answer: "Strategies should protect ecosystem processes while supporting livelihoods and development. Examples may include selective logging, conservation, ecotourism and international agreements.", exam: "Evaluate who gains, enforcement, timescale and whether use truly stays within recovery rates.", tags: ["sustainability", "management"] },
        { id: "geo-live-05", question: "Which optional ecosystem should be confirmed with your teacher?", quote: "Hot deserts or cold environments", answer: "AQA schools study one of these options. This deck keeps the structure flexible until your exact choice and case studies are confirmed.", exam: "Replace this card with your school’s named option and examples.", tags: ["option check", "course setup"] }
      ] },
      { id: "uk-landscapes", title: "UK Physical Landscapes", description: "UK overview with option-ready coastal and river landscapes sections.", cards: [
        { id: "geo-uk-01", question: "What broad pattern describes UK upland and lowland landscapes?", quote: "Uplands mainly north and west; lowlands mainly south and east", answer: "More resistant rocks and glacial history help form rugged uplands in the north and west. Softer rocks and deposition contribute to gentler lowlands in the south and east.", exam: "Use named examples from your course when describing the pattern.", tags: ["UK landscapes", "overview"] },
        { id: "geo-uk-02", question: "How does hydraulic action erode a coastline?", quote: "Air compressed in cracks", answer: "Waves force water and air into rock cracks. Repeated compression increases pressure, weakening and breaking the rock over time.", exam: "Do not confuse hydraulic action with abrasion, where sediment scrapes the rock.", tags: ["coasts", "erosion"] },
        { id: "geo-uk-03", question: "What sequence creates a headland cave, arch, stack and stump?", quote: "Crack → cave → arch → stack → stump", answer: "Erosion widens a weakness into a cave; continued erosion breaks through an arch. Weathering and gravity collapse the roof, leaving a stack that is eroded to a stump.", exam: "Add the processes at each stage, not only the landform sequence.", tags: ["coasts", "landforms"] },
        { id: "geo-uk-04", question: "How does a river’s long profile change downstream?", quote: "Gradient generally becomes gentler", answer: "Near the source vertical erosion dominates on steep slopes. Downstream, discharge and load increase, lateral erosion and deposition become more important, and the valley widens.", exam: "Explain change using energy, discharge, load and erosion—not a memorised diagram alone.", tags: ["rivers", "long profile"] },
        { id: "geo-uk-05", question: "How does a meander migrate?", quote: "Outer-bank erosion; inner-bank deposition", answer: "Faster flow and greater energy erode the outer bend, forming a river cliff. Slower water deposits material on the inner bend, forming a slip-off slope.", exam: "Link helicoidal flow to the transfer of eroded material across the channel if taught.", tags: ["rivers", "meanders"] }
      ] }
    ]}
  ]
};
