// Extra cards and close-reading notes. Existing IDs and ratings stay stable.
(() => {
  const decks = window.FLASHCARD_DATA.subjects.flatMap(s => s.decks);
  const add = (deckId, id, question, quote, answer, method, exam, tags, options) => {
    decks.find(d => d.id === deckId).cards.push({id, question, quote, answer, method, exam, tags, quiz: {question, options}});
  };
  add('macbeth', 'mac-29', 'What does Macbeth’s “false face” reveal about his choice to kill Duncan?', '“False face must hide what the false heart doth know”', 'At the end of Act 1, Macbeth decides to conceal his murderous intention behind a convincing outward appearance. He knows the difference between loyalty and betrayal, making his deception a conscious moral choice. His public role as Duncan’s host becomes a performance hiding private ambition.', 'The repeated adjective “false” connects face and heart: both outward behaviour and inward intention are corrupted. The contrast between the visible face and hidden heart develops appearance versus reality. The closing rhyme gives his decision a disturbing sense of finality.', 'Embed “false face” in a sentence about deliberate deception; contrast it with the Captain’s initial praise of his loyalty.', ['Macbeth', 'appearance', 'choice'], ['He deliberately hides a treacherous intention behind loyalty', 'He is unaware that Duncan may be harmed', 'He reveals the murder plan openly to Duncan', 'He rejects Lady Macbeth’s plan completely']);
  add('macbeth', 'mac-30', 'Why does Macbeth describe his crown as “fruitless”?', '“Upon my head they placed a fruitless crown”', 'In Act 3, Macbeth fears that Banquo’s descendants will inherit the throne. He has gained kingship through murder but believes he cannot establish a lasting dynasty. Possession of the crown therefore gives him insecurity rather than satisfaction and helps motivate further violence against Banquo and Fleance.', '“Fruitless” uses a growth metaphor to make royal power seem sterile and unproductive. A crown normally symbolises successful rule; the negative adjective empties that symbol of fulfilment. “They” shifts blame towards the witches, although Macbeth still chooses his actions.', 'Connect the metaphor to succession and paranoia. Explain how this develops ambition after Duncan’s murder.', ['Macbeth', 'Banquo', 'kingship'], ['He fears his kingship will not pass to his descendants', 'He believes all farmland in Scotland has disappeared', 'He has willingly given the throne to Malcolm', 'He has abandoned every interest in royal power']);
  add('christmas-carol', 'acc-27', 'What does “Darkness is cheap” reveal about Scrooge?', '“Darkness is cheap, and Scrooge liked it”', 'In Stave 1, Scrooge prefers an unlit home because it costs less. Dickens links an ordinary financial decision to his wider emotional life: Scrooge values saving money over warmth, comfort or human connection. The narrator’s dry tone makes this preference seem both comic and disturbing.', '“Cheap” reduces the choice to a price, revealing the dominance of money in his thinking. Darkness can also suggest ignorance, isolation or moral blindness; present these as interpretations supported by his behaviour rather than a fixed one-word code.', 'Link a precise word to Scrooge’s values, then contrast this darkness with the warmth and light of Christmas celebrations.', ['Scrooge', 'isolation', 'imagery'], ['His desire to save money reinforces his emotional isolation', 'He cannot afford a single candle because he is destitute', 'He is preparing a surprise party for Fred', 'He has already become generous and sociable']);
  add('christmas-carol', 'acc-28', 'What does Scrooge learn from the Ghost of Christmas Past’s light?', '“a bright clear jet of light”', 'The Ghost of Christmas Past illuminates experiences Scrooge has tried to leave behind. Revisiting loneliness, love and loss helps him understand how he became selfish. His attempt to extinguish the spirit’s light shows resistance to painful self-knowledge, although he cannot simply erase his past.', 'Light imagery suggests revelation and understanding. The adjectives “bright” and “clear” make the spirit’s exposure of memory difficult to ignore. Contrast the light with Scrooge’s preference for darkness to show how the supernatural challenges his habits.', 'Explain the significance of the light before connecting it to memory and the possibility of reform.', ['Ghosts', 'memory', 'imagery'], ['It symbolises the illuminating power of memory and self-knowledge', 'It proves the Ghost represents Scrooge’s future grave', 'It shows Scrooge has no memories of childhood', 'It is only a sign of the Ghost’s desire for wealth']);
  add('christmas-carol', 'acc-29', 'Why does Scrooge ask whether the future shows what “Will be” or “May be”?', '“Will be” / “May be”', 'In Stave 4, Scrooge asks whether the disturbing scenes are inevitable or conditional. The question marks a shift from passively observing events to considering how his choices could change them. Dickens presents reform as something Scrooge must practise, not something the spirits can perform for him.', 'The contrast between “Will” and “May” distinguishes certainty from possibility. The interrogative form exposes fear but also hope. Follow this turning point with his later promises and actions to demonstrate that his transformation is more than panic.', 'Use this moment to discuss free choice and redemption; support it with an example of his changed behaviour in Stave 5.', ['Scrooge', 'redemption', 'structure'], ['He wants to know whether changing his conduct can alter the future', 'He is asking for permission to return to his old behaviour', 'He believes the visions concern only Marley', 'He is certain the Ghost has no connection to his own life']);
  add('christmas-carol', 'acc-30', 'Why does Dickens call Scrooge a “second father” to Tiny Tim?', '“a second father”', 'At the end of Stave 5, Scrooge becomes a sustained source of care for Tiny Tim. The ending connects his private moral change to another person’s wellbeing. His new relationship with the Cratchits also answers his earlier belief that other people’s suffering was none of his business.', 'The familial metaphor presents generosity as a continuing relationship rather than a single payment. “Second” expands Tiny Tim’s support beyond his immediate household. The narrator’s final summary gives structural confirmation that the change lasts.', 'Contrast this ending with “surplus population” to show the movement from dehumanising the poor to caring for a particular child.', ['Tiny Tim', 'family', 'redemption'], ['His continuing care turns generosity into a lasting relationship', 'He legally replaces Bob as Tiny Tim’s only parent', 'He refuses any contact with the Cratchit family', 'He gives one donation and immediately returns to isolation']);
  add('inspector-calls', 'aic-21', 'How does Birling’s dismissal of “community” reveal his beliefs?', '“community and all that nonsense”', 'Early in Act 1, Birling rejects the idea that people owe responsibilities beyond themselves and their households. The Inspector’s arrival interrupts this lesson. Priestley makes the investigation challenge the assumptions Birling wants to pass to the younger men.', 'The dismissive noun “nonsense” belittles a moral idea instead of answering it. The interruption is a dramatic method: the structure of the scene contests Birling’s speech. Link his words to his treatment of workers to turn a claim about beliefs into an argument about consequences.', 'Contrast his dismissal with the Inspector’s image of society as one body.', ['Mr Birling', 'responsibility', 'structure'], ['He dismisses collective responsibility', 'He promises to give workers equal control of his business', 'He accepts the Inspector’s final message in advance', 'He says his wealth belongs to the whole community']);
  add('inspector-calls', 'aic-22', 'What does “half shy, half assertive” suggest about Eric?', '“half shy, half assertive”', 'The opening stage directions present Eric as uneasy and contradictory. This unsettles the appearance of a confident, harmonious family before the investigation begins. Later revelations about drinking, aggression and guilt make his early discomfort retrospectively significant.', 'The balanced repetition of “half” gives opposing qualities equal weight. These are stage directions, so explain how an actor’s posture, pauses or delivery could embody the contrast. Do not treat the phrase as dialogue Eric speaks.', 'Use the opening description as the start of an argument about Eric’s development and the family’s hidden tensions.', ['Eric', 'stagecraft', 'appearance'], ['He appears divided and uncomfortable beneath the family’s polished surface', 'He is completely confident and relaxed', 'He has already confessed publicly to the Inspector', 'He is described as physically identical to Gerald']);
  add('inspector-calls', 'aic-23', 'What does the description of Mrs Birling as “cold” suggest?', '“cold”', 'The opening stage directions establish Mrs Birling’s emotional distance. Her later refusal of Eva’s appeal gives this initial description moral significance: a person in a position to offer compassion instead judges and excludes a vulnerable woman.', 'The adjective can describe temperament rather than physical temperature. Connect this emotional coldness to a specific later decision. The stage direction shapes performance and the audience’s expectations before Mrs Birling explains her actions.', 'Analyse the description alongside her class prejudice, showing how power and lack of sympathy combine.', ['Mrs Birling', 'class', 'stagecraft'], ['Emotional distance and a lack of compassion', 'A medical illness caused by winter weather', 'Secret sympathy for Eva that she expresses openly', 'Her determination to abolish class privilege']);
  add('inspector-calls', 'aic-24', 'Why does the Inspector refer to “millions and millions” of people like Eva?', '“millions and millions”', 'Near the end, the Inspector broadens the investigation from one woman to widespread suffering. Eva’s story becomes an example of how ordinary decisions affect many vulnerable people. The audience is invited to apply the lesson beyond the Birlings’ dining room.', 'Repetition expands the scale and urgency of the warning. Explain the structural move from a named individual to a social pattern. The number is rhetorical emphasis, not evidence that the Inspector has counted an exact total.', 'Move from Eva’s particular experiences to Priestley’s wider challenge to social indifference.', ['Inspector', 'responsibility', 'inequality'], ['Eva’s suffering represents a much wider social problem', 'The Inspector claims all women have exactly the same life', 'The investigation concerns a lottery prize', 'Eva’s individual suffering is too trivial to matter']);
  add('inspector-calls', 'aic-25', 'What is the significance of the Inspector addressing “public men”?', '“public men”', 'The Inspector challenges Birling’s attempt to use civic status as protection from criticism. Holding influence in public life should increase accountability for the effects of one’s decisions. Priestley exposes the gap between respectability and moral responsibility.', 'The phrase directly targets Birling’s identity and self-importance. Explain how the address changes the power balance: the man who expects deference is being judged. Support this with Birling’s earlier references to status.', 'Discuss how Priestley tests the responsibilities attached to social and political power.', ['Inspector', 'Mr Birling', 'power'], ['Public influence brings obligations and accountability', 'Public office removes every moral duty', 'Only elected officials can ever harm others', 'Birling’s status proves every decision he makes is right']);
  add('inspector-calls', 'aic-26', 'Why is Birling’s description of the investigation as “moonshine” significant?', '“moonshine”', 'As the older characters question the Inspector’s identity, Birling dismisses the episode as something that can be disregarded. This exposes his focus on escaping consequences rather than reconsidering his conduct. The final phone call disrupts that attempted return to comfort.', 'The dismissive noun trivialises the investigation. Contrast his language with the younger characters’ continuing concern: a technical doubt about identity does not undo their admitted actions. The final twist gives this complacency a dramatic consequence.', 'Use the word to explain failed moral learning, then connect it to the ending.', ['Mr Birling', 'generation', 'structure'], ['He tries to dismiss the investigation and avoid its moral lesson', 'He promises to compensate every worker immediately', 'He openly accepts blame for Eva’s death', 'He has discovered an astronomical cause of the tragedy']);
  add('inspector-calls', 'aic-27', 'What does the informal word “squiffy” reveal at the start of the play?', '“squiffy”', 'Sheila’s description of Eric’s drinking makes a potentially serious problem sound familiar and slightly comic within the family celebration. The later investigation reveals the harmful behaviour hidden beneath this comfortable atmosphere.', 'The colloquial word creates a casual tone. Explain how later events change the audience’s understanding of the opening exchange: this is a structural contrast between a light social scene and serious consequences.', 'Connect early hints of drinking to Eric’s later confession rather than treating the word as proof of every later event.', ['Eric', 'Sheila', 'appearance'], ['Drinking is treated casually before its consequences are revealed', 'The family has already banned all alcohol permanently', 'Eric is speaking a formal legal confession', 'Sheila is describing the Inspector’s uniform']);
  add('inspector-calls', 'aic-28', 'Why does Mrs Birling describe Eva’s use of her name as “impertinent”?', '“impertinent”', 'Mrs Birling interprets Eva’s use of the name Birling as an offence against social authority. Her irritation interferes with a compassionate assessment of Eva’s need. Priestley shows a charitable institution becoming a place where status is defended instead of help offered.', 'The judgemental adjective centres Mrs Birling’s wounded pride. Ask whose perspective controls the description: it tells us about Mrs Birling’s prejudice, not an objective truth about Eva’s character.', 'Explain how language reveals an abuse of charitable influence and class judgement.', ['Mrs Birling', 'class', 'power'], ['She prioritises her own status and takes offence instead of showing compassion', 'She welcomes Eva as a relative without hesitation', 'She recognises Eva’s request as a legal order', 'She regrets having no influence in the charity']);
  add('inspector-calls', 'aic-29', 'What does Birling’s reference to a “wretched” girl’s suicide reveal?', '“wretched”', 'Birling discusses the death in terms of the trouble it may bring the family. In context, his wording can sound dismissive, reducing Eva’s suffering to an inconvenient event. Read his tone and surrounding argument together rather than assuming the adjective has only one possible meaning.', 'The adjective can mean deeply unhappy, but Birling’s focus on scandal makes an unsympathetic reading persuasive. This is a useful example of how context controls connotation: name the word, consider its range, and justify your interpretation from his priorities.', 'Link the phrase to reputation and contrast it with a character who continues to accept responsibility.', ['Mr Birling', 'reputation', 'language'], ['His concern about family trouble makes his language sound dismissive', 'He has completely stopped worrying about his reputation', 'The adjective proves Eva was morally responsible for all the family’s actions', 'He promises to give his whole business to Eva’s family']);
  add('inspector-calls', 'aic-30', 'Why does the Inspector distinguish the “young ones” from the older generation?', '“young ones”', 'The Inspector suggests younger people can be more responsive to moral teaching. Sheila and Eric’s remorse supports that hope, while their parents’ defensiveness complicates the family’s apparent unity. Age is a pattern in the play, not a guarantee that every young character always acts responsibly.', 'The collective phrase groups Sheila and Eric around their capacity to learn. Compare their actions at the end with their earlier wrongdoing to explain development rather than claiming they were innocent throughout.', 'Build a balanced paragraph on generational change: acknowledge initial harm, then analyse the different responses to it.', ['generation', 'responsibility', 'change'], ['Younger characters show greater willingness to learn and accept blame', 'Young people are shown as incapable of harming others', 'All older people in the play automatically accept the lesson', 'Age has no relationship to the characters’ responses']);
  add('living-world', 'living-depth-1', 'How can a change in one population affect an ecosystem?', 'Interdependence creates knock-on effects', 'If a prey population falls, predators may have less food; vegetation eaten by that prey may increase. Outcomes depend on other food sources and relationships. A food web helps explain several linked changes rather than assuming every organism responds identically.', '', 'Use a named small-scale ecosystem and trace a clear chain of effects.', ['Ecosystems'], ['Linked feeding relationships can cause changes in other populations', 'Only the original population can ever be affected', 'Every population increases by exactly the same amount', 'Abiotic factors immediately disappear']);
  add('living-world', 'living-depth-2', 'Why should a sustainable ecosystem strategy consider local people?', 'Conservation depends on livelihoods and participation', 'A strategy that protects habitat but removes people’s income can encourage conflict or illegal exploitation. Local employment, participation and realistic resource rules can make conservation more durable. Evaluate benefits and drawbacks with evidence from the ecosystem you study.', '', 'Explain how environmental and social outcomes interact instead of simply listing benefits.', ['Rainforest management'], ['Local livelihoods and participation can support lasting conservation', 'Local people have no influence on resource use', 'Sustainability requires every economic activity to end', 'Conservation always succeeds without funding or cooperation']);

  const techniques = {
    macbeth: [
      'Zoom in on “brave”: public praise establishes a respected starting point. The later contrast with tyranny makes his fall tragic rather than showing him as evil from the beginning.',
      'The imperatives ask the stars to conceal him. Contrast light with “black” desires to show that Macbeth understands the moral darkness of what he wants.',
      'The riding metaphor makes ambition an unstable force that can overreach and fall. “Only” isolates a selfish motive: Macbeth cannot justify regicide as a public duty.',
      'The imperative “unsex” challenges qualities Lady Macbeth associates with femininity. Analyse her attempt to suppress compassion, then compare it with her later inability to suppress guilt.',
      'The violent verb “dash’d” clashes with the tenderness expected in the image of a nursing child. Her conditional claim weaponises maternal imagery to shame Macbeth into action.',
      'The flower-and-serpent contrast separates harmless appearance from hidden danger. The serpent can carry biblical associations of temptation, making deceptive hospitality morally disturbing.',
      'Dramatic irony gives the audience knowledge Duncan lacks. His positive description of the setting makes his trust vulnerable and heightens anticipation of betrayal.',
      'The rhetorical question dramatises uncertainty rather than a straightforward report. Discuss the dagger as a possible supernatural temptation or projection of violent intention.',
      'Personifying sleep as something murdered makes guilt destroy ordinary rest. The phrase suggests psychological consequences extend beyond the physical killing of Duncan.',
      'The rhetorical question and enormous scale of “all” the ocean turn a physical bloodstain into apparently immeasurable guilt. Contrast this with Lady Macbeth’s confidence in a little water.',
      '“Little” minimises the consequence while “clears” treats moral guilt like removable dirt. Later sleepwalking creates structural irony: her certainty proves unsustainable.',
      'The metaphor “instruments” casts the witches as agents of darkness. Banquo warns that partial truths can secure trust before betrayal, offering a cautious foil to Macbeth.',
      'The paradox reverses moral categories and the repeated sounds link opposites. Explain how deceptive appearances make Macbeth’s interpretation of events unreliable.',
      'Repetition of “hail” sounds ceremonious, while “shalt” gives an uncertain future the appearance of certainty. Macbeth’s ambition makes him receptive to that promise.',
      '“Stick deep” makes fear feel like an embedded wound. Explain how Banquo’s qualities threaten Macbeth’s insecure authority even after he has obtained the crown.',
      'The imperative excludes Lady Macbeth from knowledge. The affectionate address becomes patronising in context, reversing the earlier distribution of influence in their marriage.',
      'The scorpion metaphor makes thought poisonous and threatening. The exclamation exposes emotional turmoil: achieving kingship has increased, rather than removed, his insecurity.',
      'The denial draws attention to the murder he wants to conceal. “Gory” brings private violence into a public celebration, linking personal guilt to collapsing political authority.',
      'The extended blood metaphor imagines violence as a landscape he has entered. His reasoning that continuing is easier exposes a chosen rationalisation, not the absence of alternatives.',
      'Repeated imperatives imitate her old commanding voice but cannot remove an imagined stain. “Damned” connects psychological guilt with the possibility of spiritual punishment.',
      'The scale of “all” contrasts with “little hand”. Smell imagery expands guilt beyond a visible mark, reversing her earlier claim that water could clear the deed.',
      'Repetition of “tomorrow” drains the future of progress. The rhythm suggests weariness and emptiness, offering a structural contrast with the future he once desired.',
      'The shadow metaphor makes life insubstantial; theatrical imagery reduces human endeavour to a brief performance. Connect this reading to the cost of his pursuit of power.',
      'The accumulating list presents kingship as a set of moral responsibilities. Contrast individual virtues with Macbeth’s behaviour to explain Malcolm’s role as a political foil.',
      '“Also” joins feeling with action instead of making them opposites. Macduff’s response challenges a model of masculinity that demands emotional suppression.',
      'The unexpected birth description exposes equivocation in the prophecy. Explain how Macbeth mistakes a carefully qualified statement for absolute protection.',
      'Personification gives the country a wounded body. Repetition of “bleed” moves attention from Macbeth’s private ambitions to suffering shared across Scotland.',
      'Collective acclamation contrasts with the witches’ earlier greeting. The repeated “hail” creates a structural echo that exchanges deceptive promise for public recognition.'
    ],
    'christmas-carol': [
      'The piling up of harsh participles makes greed sound habitual and relentless. Zoom in on one verb, then explain how the cumulative list intensifies the judgement.',
      'The simile suggests a hard shell protecting an isolated interior. An oyster may contain a pearl, allowing a hopeful reading of hidden worth that later events can support.',
      'Temperature imagery makes emotional coldness more powerful than literal weather. Explain how the narrator turns a physical sensation into a description of social behaviour.',
      'The rhetorical questions substitute institutions for personal compassion. Their repetition exposes how Scrooge distances himself from the collectors’ appeal.',
      'The abstract phrase reduces suffering people to an unwanted statistical excess. Its later repetition by the spirit forces Scrooge to confront the cruelty of his own language.',
      'The list of positive adjectives defines Christmas through relationships and conduct. Fred becomes a foil who challenges Scrooge without measuring happiness through wealth.',
      '“Business” changes meaning from commercial work to a duty towards humanity. Explain the reversal of Scrooge’s assumptions rather than treating the line as a business slogan.',
      'The chain is a sustained symbol of consequences created by repeated choices. “Forged” makes Marley responsible for making his own burden during life.',
      'The adjectives “solitary” and “neglected” invite pity for a child. This retrospective scene complicates the reader’s judgement of the harsh adult without excusing his later conduct.',
      'Repetition of “Home” expresses security and belonging. Fan’s affection challenges a simple claim that Scrooge has never known love.',
      'The contrast between happiness and financial cost challenges Scrooge’s definition of value. Fezziwig’s authority is shown through its emotional effects on employees.',
      'The religious metaphor “idol” makes money a rival object of worship. “Displaced” suggests that greed has gradually pushed a human relationship out of its place.',
      'The alliterative description and enormous scale suggest abundance and welcome. Connect the spirit’s appearance to generosity, then consider its later warning about deprivation.',
      'The celebratory superlative expresses delight beyond the meal’s material size. Dickens foregrounds gratitude and shared pleasure instead of mocking the family’s limited resources.',
      'The contrast between modest circumstances and positive emotions challenges wealth as a measure of happiness. The list presents affection as a collective experience.',
      'The conditional “If” leaves room for change. The prediction transforms abstract poverty into the possible death of a specific child, making indifference difficult to sustain.',
      'The biblical allusion links Tim’s vulnerability with compassion and healing. His wish asks people to remember the suffering of others, not simply admire his innocence.',
      'Personified abstractions turn social failures into vulnerable children. Naming them gives neglect a visible human form; the imperative warning demands a response.',
      'The sequence of adverbs and lack of speech give the spirit solemn authority. Silence makes Scrooge interpret the scenes himself and increases uncertainty.',
      'The casual conditional about lunch makes attendance sound like a transaction. Their detachment mirrors the way Scrooge previously reduced relationships to self-interest.',
      'The modal promise and year-long timescale turn a seasonal feeling into a continuing ethical commitment. Test the promise against his later actions.',
      'Repeated similes express lightness and joyful energy. Contrast their buoyant imagery with the heavy, cold, grasping descriptions at the opening.',
      'The concrete action of raising wages gives reform a material consequence. The promise recognises the family’s struggle instead of treating charity as a performance.',
      'Repeated “good” and the sequence of social roles present moral change across friendship, employment and personal conduct. The ending confirms consistency rather than a single generous act.',
      'The inclusive “Every One” gives the final blessing a social reach. As a closing echo of Tim’s earlier words, it reinforces belonging and the results of Scrooge’s reform.',
      'The invasive movement of fog creates a harsh setting. Connect environmental hardship to differences in access to warmth and comfort without claiming weather causes Scrooge’s selfishness.'
    ],
    'inspector-calls': [
      'The contrast between comfort and homeliness separates possessions from relationships. As stage directions, these words guide the set and audience expectations rather than a character’s speech.',
      'The repeated focus on the individual constructs a rule for living. Contrast this rule with the Inspector’s collective pronouns and test it against the harm caused by Birling’s decisions.',
      'Dramatic irony lets a later audience recognise that his certainty is mistaken. “Absolutely” intensifies his confidence, weakening trust in his other pronouncements.',
      'The prospect of an honour reveals concern with status. Analyse how external recognition functions as proof of success for Birling while the investigation questions his moral conduct.',
      'The dash corrects the language of labour as a commodity. “People” restores humanity, showing the beginning of Sheila’s moral change rather than claiming she was always without prejudice.',
      'The first-person admission takes ownership of harm. “Desperately” intensifies remorse; contrast her openness with her parents’ attempts to defend themselves.',
      'The demonstrative phrase distances Mrs Birling from the women she judges. The unfinished line can suggest prejudice so habitual that its assumptions do not need explanation.',
      'The active verb and possessive reference to influence reveal deliberate agency. Explain how power in a charitable institution becomes a means of exclusion.',
      'The inclusive “we” distributes responsibility, while the blunt verb connects separate decisions to a shared consequence. Eric’s admission challenges the family’s evasions.',
      'The casual phrasing makes aggression sound familiar. Explain how the euphemistic account exposes a threatening power imbalance rather than accepting it as an excuse.',
      'The contrast between his feelings and hers exposes unequal investment. Consider the difference between his account of rescuing her and the dependency created by his social position.',
      'The body metaphor presents people as connected parts of a whole. Collective pronouns challenge individualism, framing social responsibility as a continuing obligation.',
      'The three-part phrase and violent imagery turn a moral warning into a vision of collective suffering. A later audience can connect it to war without treating it as a literal prediction of one event.',
      'The hanging metaphor suggests the family’s own disclosures expose them. Explain how the investigation’s structure makes confession more important than the Inspector providing every fact.',
      'Sarcasm belittles the younger characters’ seriousness. The dismissive tone shows Birling defending his authority instead of addressing their moral argument.',
      'The contrast between past and present identities shows that the evening has changed Sheila’s judgement. Her refusal challenges the idea that social appearances can simply be restored.',
      'The common surname supports a representative reading, while the given name can evoke humanity’s origins. Present the allusion as an interpretation and connect it to her social role.',
      'The final call repeats the circumstances of the original investigation. This structural return creates suspense and challenges the family’s attempt to treat the lesson as finished.',
      'The sharp sound interrupts Birling’s confident speech. Analyse timing as stagecraft: a new authority arrives exactly as the established authority promotes his own values.',
      'The contrast in lighting moves from a flattering private atmosphere to harsher exposure. Explain what an audience sees and how the change reinforces scrutiny.'
    ]
  };
  Object.entries(techniques).forEach(([id, notes]) => {
    const deck = decks.find(d => d.id === id);
    notes.forEach((method, index) => { deck.cards[index].method = method; });
  });
})();
