// Edexcel GCSE History B3: Henry VIII and his ministers, 1509–40.
// Keep row order stable: IDs are used for saved progress.
(() => {
  const deck = window.FLASHCARD_DATA.subjects.find(s => s.id === 'history').decks.find(d => d.id === 'henry-pending');
  deck.title = 'Henry VIII & his ministers';
  deck.description = 'Edexcel B3 · 1509–40. Henry and Wolsey, Henry and Cromwell, and the Reformation. Based on the specification.';
  deck.pending = false;
  const rows = [
    ['How was English society organised in 1509?', 'A hierarchy dominated by landowners', 'Most people lived in the countryside and worked in agriculture. Nobles and gentry held land and local influence; merchants and craftspeople were important in towns. Social rank affected wealth, opportunity and political power.', 'Explain how the Crown relied on local elites to govern.', 'Henry and Wolsey 1509–29'],
    ['How did Henry govern England?', 'Personal monarchy supported by advisers', 'The king made major decisions, working through his council, royal household and ministers. Parliament passed laws and granted taxation; justices of the peace helped enforce authority locally. Access to Henry could create political influence.', 'Distinguish the king’s authority from the institutions implementing it.', 'Henry and Wolsey 1509–29'],
    ['What advantages did Henry inherit in 1509?', 'An established dynasty and royal resources', 'Henry VII left a more secure monarchy and substantial financial reserves. The young Henry VIII was educated, energetic and initially popular, giving him opportunities to pursue an ambitious reign.', 'Balance these strengths against the costs of Henry’s later ambitions.', 'Henry and Wolsey 1509–29'],
    ['Why is Henry described as a Renaissance prince?', 'Learning, magnificence and martial achievement', 'Henry valued languages, music, theology and physical accomplishments such as jousting. Displays of wealth and military glory helped present him as a powerful and cultured European ruler.', 'Use specific interests to support a character description.', 'Henry and Wolsey 1509–29'],
    ['What were Henry’s main aims?', 'Dynastic security, glory and royal authority', 'He wanted to secure the Tudor succession with a male heir, win prestige abroad and maintain control at home. These aims could conflict: expensive wars weakened finances and the succession problem disrupted religious policy.', 'Link an aim to a policy rather than only listing ambitions.', 'Henry and Wolsey 1509–29'],
    ['Why did Wolsey rise to power?', 'Administrative skill and royal confidence', 'Wolsey’s work organising the 1513 French campaign demonstrated his ability. His energy and willingness to handle government allowed Henry to pursue other interests. Promotion depended on continuing to satisfy the king.', 'Explain how competence translated into royal favour.', 'Henry and Wolsey 1509–29'],
    ['How did Wolsey combine Church and state power?', 'Archbishop, cardinal and Lord Chancellor', 'Wolsey became Archbishop of York in 1514 and cardinal and Lord Chancellor in 1515. His later position as papal legate gave him exceptional Church authority, while his political office placed him at the centre of government.', 'Explain why holding several offices increased influence and resentment.', 'Henry and Wolsey 1509–29'],
    ['Why did Wolsey’s wealth cause resentment?', 'Magnificence exposed his unusual rise', 'His income from Church offices supported a large household and lavish buildings such as Hampton Court. Some nobles resented the influence and display of a minister who was not from the traditional aristocracy.', 'Connect background and wealth to political enemies.', 'Henry and Wolsey 1509–29'],
    ['What did Wolsey try to do about enclosure?', 'Investigations and legal action from 1517', 'Enclosing land, especially for sheep farming, could displace tenants and reduce employment. Wolsey investigated abuses and brought cases against landowners, but resistance and compromises limited the results.', 'Explain both the purpose and limits of reform.', 'Henry and Wolsey 1509–29'],
    ['How did Wolsey reform taxation?', 'A subsidy based more closely on ability to pay', 'Assessments of income and property aimed to raise money more effectively than older fixed levies. This improved the basis of royal taxation, but Henry’s wars still created heavy financial pressure.', 'Do not treat a better tax system as unlimited royal income.', 'Henry and Wolsey 1509–29'],
    ['How did Wolsey use the courts?', 'Greater use of Star Chamber', 'Wolsey used Star Chamber to tackle wrongdoing, including cases involving powerful people. This could improve access to justice and strengthen central authority, but increased business and elite resentment created problems.', 'Explain why the same policy might help some people and alienate others.', 'Henry and Wolsey 1509–29'],
    ['What were the Eltham Ordinances of 1526?', 'Reorganisation of the royal household', 'The ordinances aimed to reduce household expenditure and regulate access to the king. Restricting the number of courtiers around Henry could also strengthen Wolsey’s position by limiting rivals’ access.', 'Link financial reform with political advantage.', 'Henry and Wolsey 1509–29'],
    ['Why did the Amicable Grant fail in 1525?', 'An unpopular levy without parliamentary approval', 'Henry sought money for war with France. Resistance, especially in East Anglia, showed that people could not or would not meet the demand. The government abandoned the levy, damaging Wolsey’s standing.', 'Explain why resistance mattered to a government with limited enforcement resources.', 'Henry and Wolsey 1509–29'],
    ['What did the Treaty of London achieve in 1518?', 'England appeared as a broker of European peace', 'Wolsey organised a wide agreement promising peace among European powers. It raised Henry’s prestige, but rivalries among the major rulers soon undermined lasting cooperation.', 'Separate short-term diplomatic prestige from durable peace.', 'Henry and Wolsey 1509–29'],
    ['What was the Field of the Cloth of Gold?', 'Henry met Francis I in 1520', 'An extravagant meeting near Calais displayed wealth, tournaments and royal friendship. It enhanced magnificence but was costly and did not create a lasting settlement of European rivalries.', 'Evaluate display and diplomatic results separately.', 'Henry and Wolsey 1509–29'],
    ['Why did foreign policy become harder in the 1520s?', 'England had less power than France or the Emperor', 'Henry wanted influence and military success, but campaigns were expensive. Charles V’s victory over Francis I at Pavia in 1525 increased imperial power without delivering Henry the French gains he hoped for.', 'Explain how another ruler’s victory could weaken England’s bargaining position.', 'Henry and Wolsey 1509–29'],
    ['Why did Henry seek an annulment from Catherine of Aragon?', 'The succession and Anne Boleyn', 'Catherine had no surviving son, and Henry feared an insecure succession. He wanted to marry Anne Boleyn and argued that marriage to his brother Arthur’s widow offended biblical law despite the earlier papal permission.', 'Combine dynastic, personal and religious arguments.', 'Henry and Wolsey 1509–29'],
    ['Why was Clement VII reluctant to grant an annulment?', 'Religious authority and imperial pressure', 'Granting it would challenge an earlier pope’s dispensation. Catherine’s nephew Charles V was highly influential, especially after the sack of Rome in 1527, making a decision against her politically dangerous.', 'Show how religious and international pressures reinforced each other.', 'Henry and Wolsey 1509–29'],
    ['Why did the Blackfriars proceedings fail in 1529?', 'No successful judgement in England', 'Wolsey and Cardinal Campeggio heard the case, but Catherine resisted and the proceedings were adjourned. The case returned to papal control, frustrating Henry’s expectation that Wolsey could secure a solution.', 'Connect the failed proceedings to Wolsey’s loss of usefulness.', 'Henry and Wolsey 1509–29'],
    ['Why did Wolsey fall from power?', 'Failure over the annulment and hostile rivals', 'Henry lost confidence when Wolsey failed to end his marriage. Anne Boleyn and other enemies increased pressure against him. In 1529 he lost the chancellorship after a charge of praemunire; he died in 1530 before trial for treason.', 'Rank causes and explain why royal favour was decisive.', 'Henry and Wolsey 1509–29'],
    ['Why did Cromwell rise after Wolsey’s fall?', 'Legal skill and a workable route to Henry’s goal', 'Cromwell had served Wolsey and gained experience in law, finance and Parliament. He won Henry’s confidence by helping use legislation to challenge papal authority and resolve the marriage problem.', 'Connect expertise to the specific problem Henry wanted solved.', 'Henry and Cromwell 1529–40'],
    ['How did Cromwell use Parliament?', 'Make royal policy enforceable through statute', 'Parliament passed measures restricting papal authority and strengthening the Crown’s control of the Church. Statutes gave the changes a legal basis and helped bind political elites to the new settlement.', 'Explain why legislation mattered, rather than saying Parliament became democratic.', 'Henry and Cromwell 1529–40'],
    ['Why was the Act in Restraint of Appeals important in 1533?', 'Church cases could no longer be appealed to Rome', 'The law prevented appeals to the pope and asserted England’s independent authority. It enabled the marriage case to be settled in England without Catherine overturning the judgement through Rome.', 'Connect the law directly to the annulment.', 'Henry and Cromwell 1529–40'],
    ['What was Cranmer’s role in Henry’s marriage settlement?', 'Archbishop of Canterbury from 1533', 'Cranmer declared Henry’s marriage to Catherine invalid in 1533 and confirmed the validity of his marriage to Anne. His position allowed Henry’s wishes to be implemented through English Church authority.', 'Distinguish Cranmer’s ecclesiastical judgement from Cromwell’s legislative work.', 'Henry and Cromwell 1529–40'],
    ['Why did Anne Boleyn fall in 1536?', 'Loss of favour, succession anxiety and accusations', 'Anne had not produced a surviving son and Henry’s interest shifted towards Jane Seymour. Cromwell helped organise the investigation leading to charges of adultery and treason. Anne was executed; the accusations should not be treated as proven facts.', 'Separate allegations used against Anne from established causes of her vulnerability.', 'Henry and Cromwell 1529–40'],
    ['Why did Henry marry Jane Seymour?', 'A new marriage and hope of a male heir', 'Jane attracted Henry while Anne’s position weakened. She presented a more conventionally obedient image. Her marriage offered another chance to secure the succession, and she gave birth to Edward in 1537.', 'Relate the marriage to Henry’s continuing dynastic priority.', 'Henry and Cromwell 1529–40'],
    ['What was the significance of Jane Seymour’s death?', 'Edward survived, but Jane died in 1537', 'Jane died shortly after childbirth. Henry finally had a legitimate son, strengthening the dynasty’s position, but an infant heir remained vulnerable and the king would later seek another marriage.', 'Explain why a male birth improved security without removing every risk.', 'Henry and Cromwell 1529–40'],
    ['Why was the marriage to Anne of Cleves arranged?', 'A diplomatic alliance in 1540', 'Cromwell promoted a German alliance when cooperation between France and the Emperor appeared threatening. The marriage was intended to improve England’s security after the break with Rome.', 'Explain the international context rather than treating it only as a personal choice.', 'Henry and Cromwell 1529–40'],
    ['Why did the Cleves marriage damage Cromwell?', 'Henry rejected a match Cromwell had promoted', 'Henry disliked the marriage, which was annulled in 1540. The diplomatic value of the alliance had also weakened. Cromwell’s rivals could use Henry’s disappointment to undermine the minister’s judgement.', 'Link the failed policy to enemies exploiting lost favour.', 'Henry and Cromwell 1529–40'],
    ['How did Cromwell reorganise royal finance?', 'Specialised administration for new revenues', 'The dissolution brought extensive former Church property under royal control. Bodies such as the Court of Augmentations, established in 1536, administered the resulting income and lands.', 'Explain why expanded responsibilities required new machinery.', 'Henry and Cromwell 1529–40'],
    ['How did central government develop under Cromwell?', 'More specialised administration and a smaller council', 'Government relied increasingly on written records and specialist departments. By 1540 the Privy Council was a smaller working body. Historians debate how far these developments were a revolution or extensions of earlier practice.', 'Avoid assuming all government change was invented by one minister.', 'Henry and Cromwell 1529–40'],
    ['Why did Cromwell fall in 1540?', 'Royal disappointment combined with factional hostility', 'The Cleves marriage damaged his standing, while conservative rivals such as Norfolk opposed his influence and religious direction. Accusations of treason and heresy helped destroy him once Henry withdrew protection; he was executed in July.', 'Explain how several causes combined rather than relying only on the marriage.', 'Henry and Cromwell 1529–40'],
    ['Why had Henry been called Defender of the Faith?', 'A papal title awarded in 1521', 'Henry defended Catholic teaching against Luther in a published work and received the title from the pope. His later break with Rome therefore did not begin as a rejection of every Catholic belief.', 'Use this to show change in authority alongside continuity in belief.', 'Reformation 1529–40'],
    ['What did the Act of Succession of 1534 establish?', 'The succession through Anne Boleyn’s children', 'The law supported Henry’s marriage to Anne and excluded Mary from the succession under that settlement. An oath tested acceptance and made the marriage issue a public question of loyalty.', 'Do not confuse succession legislation with royal supremacy.', 'Reformation 1529–40'],
    ['What did the Act of Supremacy of 1534 do?', 'Recognised Henry as head of the English Church', 'It placed the English Church under royal rather than papal supremacy. Religious authority and obedience to the king became closely linked, giving opposition political as well as spiritual consequences.', 'Explain a consequence for both power and dissent.', 'Reformation 1529–40'],
    ['How did Cromwell enforce the religious settlement?', 'Oaths, investigations and treason legislation', 'The government required acceptance of the new order and investigated opponents. Treason laws made denial of royal authority dangerous, helping turn dissent into a punishable challenge to the state.', 'Show how laws could change behaviour through the threat of punishment.', 'Reformation 1529–40'],
    ['Why was Elizabeth Barton seen as a threat?', 'Religious prophecy challenged Henry’s marriage policy', 'Barton, known as the Nun of Kent, claimed visions condemning Henry’s proposed marriage. Her religious reputation and contacts could give opposition credibility; she was executed in 1534.', 'Explain why a religious voice could become politically dangerous.', 'Reformation 1529–40'],
    ['Why was John Fisher’s opposition significant?', 'A bishop defended papal authority and Catherine', 'Fisher’s status gave weight to resistance. His refusal to accept royal supremacy challenged the legitimacy of Henry’s religious changes, and he was executed in 1535.', 'Connect the opponent’s position to the threat he represented.', 'Reformation 1529–40'],
    ['Why did Thomas More’s resistance matter?', 'A respected former Lord Chancellor', 'More’s reputation as a scholar and former minister made his refusal to accept the new settlement especially damaging. He was convicted of treason and executed in 1535 after refusing to acknowledge royal supremacy.', 'Explain why prominent opponents mattered beyond their numbers.', 'Reformation 1529–40'],
    ['How far did religious practice change under Henry?', 'Reform alongside Catholic continuity', 'Cromwell and Cranmer encouraged changes including access to an English Bible. Yet Henry retained many traditional beliefs: the Six Articles of 1539 reaffirmed teachings including transubstantiation and clerical celibacy.', 'Do not equate the break with Rome with immediate full Protestantism.', 'Reformation 1529–40'],
    ['What services did monasteries provide?', 'Worship and local economic and social roles', 'Religious houses could provide employment, hospitality, charity and some care or education. Their importance varied, but closure could affect many people beyond monks and nuns.', 'Explain a local effect using a specific function.', 'Reformation 1529–40'],
    ['Why did Henry dissolve the monasteries?', 'Wealth, control and religious criticism', 'Monasteries held valuable land and income. Dissolution increased royal resources and removed institutions associated with the old religious order. Reports of misconduct supplied a justification for action.', 'Assess financial and religious motives together.', 'Reformation 1529–40'],
    ['What was the significance of the investigations of 1535?', 'Assessing wealth and reporting on religious houses', 'The Valor Ecclesiasticus surveyed Church wealth, while visitors investigated religious houses and reported alleged abuses. Such reports helped justify closure, but their purpose means allegations require careful evaluation.', 'Distinguish the financial survey from reports of misconduct.', 'Reformation 1529–40'],
    ['How did dissolution develop from 1536 to 1540?', 'Smaller houses first, then the remaining monasteries', 'Legislation in 1536 targeted smaller monasteries. Further closures and surrenders followed, and legislation in 1539 confirmed the Crown’s acquisition of surrendered houses. By 1540 monastic life had been largely dismantled.', 'Use chronology to explain a process, not a single event.', 'Reformation 1529–40'],
    ['Who gained and lost from dissolution?', 'Crown and purchasers gained; communities faced disruption', 'The Crown acquired property and buyers obtained former monastic estates. Some religious people received pensions, but others lost their way of life; communities could lose employment, charity and religious centres.', 'Compare groups instead of assuming everybody benefited equally.', 'Reformation 1529–40'],
    ['Why did the Pilgrimage of Grace begin in 1536?', 'Religious grievances mixed with wider discontent', 'Closure of monasteries and fears for traditional worship were central. Anger at advisers such as Cromwell, taxation fears and economic grievances also encouraged opposition in northern England.', 'Show why people with different grievances joined the same movement.', 'Reformation 1529–40'],
    ['How did the northern rebellions develop?', 'Lincolnshire protest followed by a larger Yorkshire movement', 'The Lincolnshire rising began in autumn 1536. In Yorkshire, Robert Aske helped organise a much larger movement known as the Pilgrimage of Grace, with rebels presenting themselves as loyal subjects defending religion.', 'Explain the distinction between opposing advisers and openly rejecting the king.', 'Reformation 1529–40'],
    ['How did Norfolk respond to the rebels?', 'Negotiation when immediate force was risky', 'Facing a large rebel force, Norfolk negotiated and offered concessions and a pardon in the king’s name. Promises of addressing grievances encouraged rebels to disperse.', 'Explain why negotiation bought time for royal authority.', 'Reformation 1529–40'],
    ['Why did the Pilgrimage fail to reverse Henry’s policies?', 'Dispersal weakened the movement', 'Rebels trusted assurances and lost their collective military strength. Renewed unrest in 1537 gave Henry a pretext for repression; Aske and other leaders were executed and dissolution continued.', 'Link the sequence of events to the government’s eventual advantage.', 'Reformation 1529–40'],
    ['What connects the falls of Wolsey and Cromwell?', 'Power depended on the king’s confidence', 'Both rose through useful service and gained enemies. When major policies failed to satisfy Henry, rivals became more effective because royal protection weakened.', 'Compare different failures: the annulment for Wolsey and the Cleves match among Cromwell’s problems.', 'Exam practice'],
    ['How do you explain why a minister fell?', 'A cause must lead to loss of power', 'Support each reason with precise knowledge, then explain how it reduced Henry’s trust or strengthened rivals. Finish by showing how causes worked together or deciding which was most important.', 'Practise a paragraph on Wolsey’s failure to secure the annulment.', 'Exam practice'],
    ['How do you judge whether the Reformation was mainly about money?', 'Weigh motives against the sequence of events', 'Use financial gains from dissolution alongside Henry’s succession problem, claims to sovereignty and religious influences. Explain what each factor accounts for and why one may be more convincing overall.', 'Give a supported judgement, not simply one paragraph for each side.', 'Exam practice']
  ];
  deck.cards = rows.map(([question, quote, answer, exam, topic], index) => ({id:`henry-b3-${index+1}`,question,quote,answer,exam,tags:[topic]}));
})();
