// Medicine through Time cards adapted from the user's revision notes, October 2026.
// This provider runs after the older card providers and replaces Medicine only.
// New IDs keep confidence recorded for the old questions separate from these cards.
(() => {
  const deck = window.FLASHCARD_DATA?.subjects.flatMap(subject => subject.decks)
    .find(candidate => candidate.id === 'medicine');
  if (!deck) return;

  const card = (number, period, question, quote, answer, exam, theme, options) => ({
    id: `medicine-notes-20261010-${String(number).padStart(2, '0')}`,
    question,
    quote,
    answer,
    exam,
    tags: [period, theme],
    ...(options ? { quiz: { question, options } } : {})
  });

  // Keep legacy confidence recoverable without filling the old 60-entry cloud document.
  deck.retiredCardIds = deck.cards.map(item => item.id);
  deck.cloudRatingScope = 'medicine-notes-20261010';
  deck.description = 'Medicine through Time and the Western Front, built from your notes: 60 cards and 30 quiz questions covering causes, prevention, treatment and care.';
  deck.cards = [
    card(1, 'medieval',
      'What were the Four Humours, and how were they meant to affect health?',
      'Blood, phlegm, black bile and yellow bile',
      'Hippocratic medicine taught that health depended on a balance of these four bodily fluids. An imbalance was thought to cause illness. Galen developed this explanation, which remained influential in medieval medicine even though it was incorrect.',
      'Explain how belief in imbalance led to treatments such as bleeding and purging.',
      'ideas', ['Health depended on balancing four bodily fluids', 'Illness was always caused by bacteria', 'Blood circulated through capillaries', 'Every disease came from inherited genes']),
    card(2, 'medieval',
      'How did Galen’s Theory of Opposites guide treatment?',
      'Treat a supposed imbalance with its opposite',
      'Galen linked the humours to qualities such as hot, cold, wet and dry. A doctor might treat an illness thought to be cold and wet with something hot and dry. The treatment followed an ancient theory rather than an understanding of germs.',
      'Use an example to connect a belief about causes to a chosen treatment.',
      'treatment', ['Use a remedy with qualities opposite to the supposed imbalance', 'Give every patient the same vaccine', 'Replace an injured organ with a transplant', 'Treat infections using penicillin']),
    card(3, 'medieval',
      'How did religious explanations and miasma explain illness?',
      'God’s punishment and harmful air',
      'Some people understood disease as punishment for sin or a test from God. Miasma was the belief that foul air, often associated with rotting waste, caused illness. These explanations could exist alongside the Four Humours rather than replacing one another.',
      'Avoid presenting everyone as having one identical belief about disease.',
      'ideas', ['Disease could be explained by sin or foul air', 'Doctors understood all disease-causing bacteria', 'The NHS diagnosed disease using scans', 'People had rejected religion as an explanation']),
    card(4, 'medieval',
      'What was a regimen sanitatis meant to do?',
      'Advice for keeping the body healthy',
      'A regimen sanitatis gave guidance on habits such as food, exercise, sleep and cleanliness. A physician could tailor advice to a patient’s constitution and humours. It aimed to prevent illness by keeping the body in balance.',
      'Separate prevention before illness from treatment after symptoms appear.',
      'prevention', ['Guide daily habits to maintain health and balance', 'Identify the bacterium that caused tuberculosis', 'Train battlefield stretcher bearers', 'Provide an antibiotic for every illness']),
    card(5, 'medieval',
      'Why did medieval practitioners use bloodletting and purging?',
      'Remove a supposed excess of a humour',
      'Bloodletting removed blood by opening a vein, applying leeches or using cupping. Purging used substances that caused vomiting or emptied the bowels. Practitioners thought these methods restored balance; they could instead weaken a sick person.',
      'Explain the reasoning at the time, then distinguish it from whether the treatment worked.',
      'treatment', ['To remove a supposed excess and restore the humours’ balance', 'To replace blood lost in battle', 'To kill a known bacterium with an antibiotic', 'To make a patient immune through vaccination']),
    card(6, 'medieval',
      'Why were herbal remedies common in medieval medicine?',
      'Available ingredients and inherited practical knowledge',
      'People used plants such as mint, camomile and ginger in remedies. Ingredients were accessible, and recipes were passed on through households and practitioners. Some could ease symptoms, but that does not mean people understood the cause of the illness or that every remedy was effective.',
      'Describe both practical experience and the limits of medical knowledge.',
      'treatment'),
    card(7, 'medieval',
      'How did a physician, an apothecary and a barber-surgeon differ?',
      'Diagnosis, remedies and practical procedures',
      'University-trained physicians diagnosed illness and advised wealthy patients. Apothecaries prepared and sold remedies. Barber-surgeons performed practical work such as tooth extraction and bloodletting, usually learning through apprenticeship rather than a university medical degree.',
      'Compare training, work and cost rather than calling every practitioner untrained.',
      'care', ['Physicians diagnosed, apothecaries made remedies and barber-surgeons performed procedures', 'All three were NHS nurses', 'Only apothecaries could operate on battlefield wounds', 'All three received identical university training']),
    card(8, 'medieval',
      'What care could a medieval hospital offer?',
      'Religious care alongside practical support',
      'Many hospitals were religious foundations offering food, shelter, prayer and nursing. Some provided herbal remedies or other treatment. Their role was often to care for people rather than cure a disease, and provision varied between hospitals.',
      'Do not reduce all medieval hospitals to prayer alone; explain their limited medical role.',
      'care'),
    card(9, 'medieval',
      'How did the Church help Galen’s ideas remain influential?',
      'Authority, education and accepted explanations',
      'The Church played an important role in education and the preservation of medical texts. Galen’s account of a purposeful body fitted Christian ideas about creation. Respect for ancient authorities and established teaching made challenges less likely, although the Church was not the only reason for continuity.',
      'Link the Church’s influence to acceptance of Galen; add another factor in a judgement.',
      'ideas'),
    card(10, 'medieval',
      'Why was it hard to test Galen’s anatomy in the medieval period?',
      'Limited human dissection, not a universal ban',
      'Human dissection was uncommon and access to bodies was limited. Teaching often placed more weight on authoritative texts than new observations. Dissections did take place in parts of medieval Europe, so it is inaccurate to say that all human dissection was illegal.',
      'Explain restricted opportunities and deference to texts without inventing a blanket ban.',
      'ideas'),
    card(11, 'medieval',
      'Why did people struggle to explain the Black Death of 1348–49?',
      'Existing beliefs could not identify the infection',
      'People used explanations such as God’s punishment, miasma and astrology to make sense of the epidemic. They did not understand plague bacteria or their transmission. A devastating outbreak did not automatically produce a correct new explanation of disease.',
      'Use the Black Death to show the limits of medieval knowledge, not a sudden discovery of germs.',
      'ideas'),
    card(12, 'medieval',
      'How did people try to prevent or treat the Black Death?',
      'Religious responses and attempts to avoid bad air',
      'Responses included prayer, confession, pilgrimage and, for some, self-flagellation. People also used strong-smelling herbs or tried to keep streets cleaner because they feared miasma. These measures followed their beliefs but did not reliably prevent or cure plague.',
      'Connect each response to its explanation of disease; do not claim herbs killed plague bacteria.',
      'prevention'),

    card(13, 'renaissance',
      'How did Vesalius challenge Galen in 1543?',
      'On the Fabric of the Human Body',
      'Vesalius dissected human bodies and published detailed anatomical illustrations in 1543. Observation revealed errors in anatomy inherited from Galen, who had relied heavily on animals. His work encouraged doctors to check accepted accounts against the human body itself.',
      'Explain why human observation could expose errors in animal-based anatomy.',
      'individuals', ['He used human dissection to expose errors in Galen’s anatomy', 'He discovered the smallpox vaccine', 'He introduced the NHS', 'He proved that tuberculosis was caused by a bacterium']),
    card(14, 'renaissance',
      'What did William Harvey demonstrate in 1628?',
      'The heart pumps blood around the body',
      'Harvey used observations, experiments and calculations to argue that blood circulates rather than being continually made and used up. The heart acts as a pump. He challenged Galen but could not see the tiny capillaries connecting arteries and veins.',
      'Distinguish Harvey’s evidence for circulation from the later observation of capillaries.',
      'individuals', ['Blood circulates around the body, driven by the heart', 'Blood is continually made in the liver and used up', 'Blood contains four separate types of bacteria', 'Every infection can be cured by bloodletting']),
    card(15, 'renaissance',
      'Why did better anatomical knowledge not immediately produce better treatments?',
      'Knowledge changed faster than everyday practice',
      'Vesalius and Harvey improved understanding of the body, but they did not reveal the causes of most diseases or provide new cures. Some practitioners resisted their findings, while patients still expected familiar remedies such as bleeding. Discovery and widespread medical change were not the same thing.',
      'Explain one new discovery and one reason its practical impact remained limited.',
      'treatment', ['New anatomical knowledge did not itself explain disease or supply new cures', 'All doctors instantly abandoned older treatments', 'The discoveries introduced antibiotics immediately', 'The NHS refused to employ Renaissance doctors']),
    card(16, 'renaissance',
      'How did Thomas Sydenham change the study of disease?',
      'Observe symptoms and compare illnesses',
      'Sydenham carefully recorded symptoms and distinguished diseases by the patterns he observed. His Observationes Medicae appeared in 1676. He encouraged attention to the patient and the course of an illness, although he did not discover microbes as its cause.',
      'Identify the change in method without claiming that Sydenham developed germ theory.',
      'individuals', ['He observed symptoms and classified diseases more carefully', 'He discovered DNA’s structure', 'He replaced all remedies with vaccination', 'He proved that every disease had the same symptoms']),
    card(17, 'renaissance',
      'Which treatments continued from medieval medicine into the Renaissance?',
      'Bleeding, purging and herbal remedies',
      'Many practitioners continued to use bloodletting, purging and familiar plant-based remedies. Humoural thinking, established training and patient expectations supported continuity. New anatomical discoveries did not make older methods disappear overnight.',
      'Give a treatment example and explain why it persisted, rather than simply saying little changed.',
      'treatment'),
    card(18, 'renaissance',
      'What were chemical remedies and transference?',
      'New approaches did not always mean effective cures',
      'Some practitioners tried chemical remedies associated with alchemy, including preparations containing minerals or metals. Transference was the belief that an illness could be passed from a person to an object or animal. Both widened the range of attempted treatments without reliably explaining disease.',
      'Distinguish a change in the treatment attempted from evidence that it worked.',
      'treatment'),
    card(19, 'renaissance',
      'How did the Dissolution of the Monasteries affect medical care?',
      'The loss of some religious institutions',
      'Henry VIII’s closure of monasteries in the 1530s removed institutions that had provided care and support. This disrupted provision, but it did not close every hospital permanently. Some institutions survived or were refounded, and other forms of care developed.',
      'Explain disruption to access without claiming that all hospitals vanished.',
      'care'),
    card(20, 'renaissance',
      'How did medical training and care change during the Renaissance?',
      'More regulation and more printed medical knowledge',
      'Professional organisations and licensing increasingly regulated some practitioners. Printed books made medical ideas more accessible. Hospitals and pesthouses could separate people with infectious disease, but standards, access and practical training remained uneven.',
      'Make a qualified comparison: improvements were not the same everywhere or for everyone.',
      'care'),
    card(21, 'renaissance',
      'Why did the printing press matter for medicine?',
      'Ideas and illustrations could reach more readers',
      'Printing made it easier to reproduce medical books and detailed diagrams, including Vesalius’s work. Scholars could compare, discuss and challenge ideas beyond a single institution. Wider communication supported change, though it also circulated older beliefs.',
      'Name a medical example, then explain how communication helped its influence spread.',
      'ideas', ['It spread medical ideas and illustrations to more readers', 'It sterilised surgical equipment', 'It made microscopes unnecessary', 'It automatically proved all printed claims correct']),
    card(22, 'renaissance',
      'How did the Royal Society encourage medical and scientific change?',
      'Experiments, debate and shared results',
      'Founded in 1660 and supported by Charles II, the Royal Society encouraged observation and experiment. Philosophical Transactions began in 1665 and helped circulate findings. These networks made it easier to discuss evidence and challenge accepted explanations.',
      'Explain the link between organised communication and the testing of new ideas.',
      'ideas', ['It encouraged experiments and shared findings through meetings and publications', 'It banned the discussion of new observations', 'It introduced compulsory smallpox vaccination in 1660', 'It established the NHS in 1665']),
    card(23, 'renaissance',
      'Why did seeing microorganisms not immediately establish germ theory?',
      'Observation alone did not prove the cause of disease',
      'Improved microscopes allowed observers such as Leeuwenhoek to see tiny organisms in the seventeenth century. Seeing them did not demonstrate that particular microbes caused particular diseases. That connection required later experiments and research.',
      'Separate the invention of a useful instrument from the explanation it eventually helped support.',
      'ideas'),
    card(24, 'renaissance',
      'How did people respond to the Great Plague of 1665?',
      'Older beliefs alongside attempts to restrict contact',
      'People used prayer, herbs and measures against miasma. London authorities shut infected households and restricted movement; cats and dogs were killed in a mistaken attempt to reduce disease. Eyam’s later self-isolation illustrates a local attempt to limit spread, not proof that people understood plague bacteria.',
      'Compare continuity in beliefs with changes in organisation and isolation.',
      'prevention'),

    card(25, 'industrial',
      'What did Pasteur’s work in 1861 challenge?',
      'Microorganisms came from the environment, not spontaneous generation',
      'Pasteur’s experiments showed that microorganisms caused decay and did not simply appear from rotting matter. This undermined spontaneous generation and laid foundations for germ theory. Applying the explanation to human disease and treatment took further work.',
      'Explain why the theory mattered, then distinguish discovery from later medical application.',
      'ideas', ['The belief that microorganisms appeared spontaneously from decaying matter', 'The existence of the heart', 'The need for any scientific experiment', 'The fact that humans have bones']),
    card(26, 'industrial',
      'How did Robert Koch build on germ theory?',
      'Specific microorganisms cause specific diseases',
      'Koch developed methods to identify and study bacteria. In 1882 he identified the bacterium responsible for tuberculosis. Linking a particular microbe to a particular disease gave researchers a clearer target for prevention and treatment.',
      'Show how Koch’s work made Pasteur’s general explanation more specific.',
      'individuals', ['He identified specific bacteria responsible for particular diseases', 'He argued that all diseases came from one humour', 'He discovered blood circulation in 1628', 'He introduced the first NHS hospitals']),
    card(27, 'industrial',
      'What did Edward Jenner do in 1796 and 1798?',
      'Smallpox vaccination using cowpox',
      'Jenner tested protection against smallpox using cowpox in 1796 and published his findings in 1798. His vaccine offered a safer alternative to variolation. It worked before anyone could explain it using germ theory, showing that practical prevention could precede a correct explanation.',
      'Keep the date of the experiment separate from the date of publication.',
      'individuals', ['He tested cowpox vaccination in 1796 and published in 1798', 'He discovered penicillin in 1796 and created the NHS in 1798', 'He identified tuberculosis bacteria in 1796', 'He made routine polio vaccination compulsory in 1798']),
    card(28, 'industrial',
      'Why did some people resist smallpox vaccination?',
      'Doubts, risks and objections to compulsion',
      'Some doubted a treatment involving material from cows or distrusted it because its mechanism was unexplained. Early techniques also raised safety concerns. Later opponents objected to government compulsion. Support and resistance varied; medical opinion was not uniformly against Jenner.',
      'Identify a specific reason for opposition rather than treating resistance as simple ignorance.',
      'prevention'),
    card(29, 'industrial',
      'When did the government make infant smallpox vaccination compulsory?',
      'The Vaccination Act of 1853',
      'The 1853 Act made smallpox vaccination compulsory for infants in England and Wales. Later legislation strengthened enforcement. This showed a growing willingness to intervene in public health, even though opposition continued.',
      'Use 1853 for the compulsory law; do not confuse it with later enforcement measures.',
      'government', ['1853', '1796', '1665', '1948']),
    card(30, 'industrial',
      'How did John Snow investigate the Soho cholera outbreak in 1854?',
      'Cases clustered around the Broad Street pump',
      'Snow mapped deaths and investigated the water people drank. He linked the outbreak to contaminated water from the Broad Street pump and persuaded authorities to remove its handle. He challenged miasma before the bacterium was identified, but his explanation was not immediately accepted by everyone.',
      'Explain the evidence behind his conclusion, not just that he removed a pump handle.',
      'individuals', ['He linked cholera cases to contaminated drinking water', 'He proved that all cholera came from cold weather', 'He invented an antibiotic for cholera', 'He blamed the outbreak on an imbalance of black bile']),
    card(31, 'industrial',
      'How did the Public Health Acts of 1848 and 1875 differ?',
      'Enabling action became compulsory duties',
      'The 1848 Act allowed local health boards and improvements but did not impose the same duties everywhere. The 1875 Act consolidated law and required local authorities to address sanitation, including sewers, clean water and waste. Government intervention became more systematic.',
      'Explain the change in obligation; do not describe both Acts as equally compulsory.',
      'government', ['1848 largely enabled action; 1875 imposed wider sanitation duties', 'Both Acts introduced the NHS', '1848 required antibiotics; 1875 banned hospitals', '1875 ended all local responsibility for public health']),
    card(32, 'industrial',
      'Why were London’s new sewers important?',
      'Engineering reduced exposure to contaminated waste',
      'Joseph Bazalgette’s sewer system, developed from the late 1850s, diverted sewage away from central London. It improved sanitation and helped reduce waterborne disease. Public pressure, funding and engineering produced a benefit even while miasma remained influential.',
      'Link infrastructure to disease transmission and explain the role of government investment.',
      'prevention'),
    card(33, 'industrial',
      'How did chloroform change surgery after 1847?',
      'Anaesthesia reduced pain during operations',
      'James Simpson promoted chloroform as an anaesthetic in 1847. It allowed longer and more complex operations because patients could be unconscious. It carried risks and did not prevent infection, so solving pain alone did not make surgery safe.',
      'Distinguish pain, infection and blood loss as separate problems in surgery.',
      'treatment'),
    card(34, 'industrial',
      'How did Joseph Lister use germ theory to improve surgery?',
      'Carbolic acid as an antiseptic',
      'From 1865, Lister used carbolic acid to reduce infection in wounds and during operations. Pasteur’s work helped him connect infection with microorganisms. His methods required changes in practice and were not accepted immediately by every surgeon.',
      'Make the chain clear: scientific explanation led to a practical method of reducing infection.',
      'treatment'),
    card(35, 'industrial',
      'What is the difference between antiseptic and aseptic surgery?',
      'Kill germs versus keep them out',
      'Antiseptic methods aim to destroy microorganisms, for example with carbolic acid. Aseptic methods aim to prevent contamination, using sterilised instruments, clean theatres and protective clothing. By the late nineteenth century, improved equipment and routines supported safer operations.',
      'Use a distinct example for each method rather than treating the words as interchangeable.',
      'treatment'),
    card(36, 'industrial',
      'How did Florence Nightingale help change nursing and hospitals?',
      'Cleanliness, trained nursing and hospital design',
      'Nightingale campaigned for clean, well-ventilated hospitals and wrote Notes on Nursing. Her training school opened in 1860, helping make nursing a skilled profession. Sanitary repairs and other changes also mattered in the Crimean War; falling deaths were not simply her achievement alone.',
      'Explain her contribution while acknowledging the sanitary commission and wider reforms.',
      'care'),

    card(37, 'modern',
      'How did DNA research improve understanding of disease?',
      'DNA structure in 1953; Human Genome Project, 1990–2003',
      'Understanding DNA’s structure helped explain how genetic information is inherited. The Human Genome Project mapped and sequenced human DNA, supporting research into genetic contributions to disease. Not all illness is genetic, and a discovery does not automatically provide a cure.',
      'Connect research to a new explanation of disease without claiming that genes explain every illness.',
      'ideas', ['It helped explain inherited and genetic contributions to disease', 'It proved that every illness was caused by bacteria', 'It made all infectious diseases disappear', 'It showed that smoking could not affect health']),
    card(38, 'modern',
      'What did research in the 1950s show about smoking and lung cancer?',
      'Evidence linked smoking with a greater risk of lung cancer',
      'Studies by researchers including Richard Doll and Austin Bradford Hill established a strong link between smoking and lung cancer. This strengthened explanations based on lifestyle and environmental risks rather than infection alone. Smoking increases risk; it is not the only possible cause of lung cancer.',
      'Explain how evidence about risk influenced prevention rather than claiming every smoker develops cancer.',
      'ideas', ['Smoking was strongly linked to a greater risk of lung cancer', 'Lung cancer was always caused by smallpox', 'Smoking removed the need for medical treatment', 'Every case of lung cancer was inherited']),
    card(39, 'modern',
      'How have scans and laboratory tests changed diagnosis?',
      'Evidence from inside the body',
      'X-rays, CT scans and ultrasound let doctors investigate inside the body without an exploratory operation in many cases. Laboratory tests can identify infections and other abnormalities. They improve the accuracy and timing of diagnosis, although tests have limitations and are not treatments themselves.',
      'Keep diagnosis separate from treatment and explain what the technology lets a doctor see or measure.',
      'care'),
    card(40, 'modern',
      'Were routine modern childhood vaccinations made compulsory in the UK?',
      'Routine vaccination programmes are not compulsory',
      'Diphtheria immunisation expanded nationally in the 1940s; polio vaccination began in 1956 and tetanus in 1961. Routine childhood vaccination is offered and encouraged rather than compulsory. This differs from nineteenth-century legislation requiring infant smallpox vaccination.',
      'Distinguish introducing a national programme from legally compelling people to take part.',
      'prevention', ['No: routine programmes offered and encouraged vaccination', 'Yes: all routine childhood vaccines became compulsory in 1940', 'Yes: the NHS required every child to receive penicillin', 'No: the UK never introduced national vaccination programmes']),
    card(41, 'modern',
      'What did the Clean Air Act and smoke-free law try to prevent?',
      'Harm from pollution and second-hand smoke',
      'The Clean Air Act of 1956 tackled smoke pollution after the Great Smog. In England, smoke-free rules for enclosed public places and workplaces came into force on 1 July 2007 under the Health Act 2006. This did not ban smoking everywhere.',
      'Use 2006 for the Act and 2007 for implementation in England; specify what was restricted.',
      'government', ['Smoke-free rules in enclosed public places and workplaces began in England in 2007', 'All smoking everywhere in the UK was banned in 2006', 'The Clean Air Act introduced the Four Humours', 'The smoke-free law abolished treatment for lung cancer']),
    card(42, 'modern',
      'What was a “magic bullet” in early twentieth-century medicine?',
      'A chemical treatment targeting a disease-causing organism',
      'Researchers sought chemicals that would attack a pathogen without harming the patient too much. Salvarsan 606, developed through Ehrlich and Hata’s work and introduced in 1910, treated syphilis. It was a targeted chemical drug, not penicillin and not a cure for every disease.',
      'Use Salvarsan as evidence of more targeted treatment, while recognising its risks and limitations.',
      'treatment'),
    card(43, 'modern',
      'What did Alexander Fleming observe in 1928?',
      'Penicillin mould inhibited bacterial growth',
      'Fleming noticed that bacteria did not grow around a contaminating mould on a culture plate. This led him to investigate penicillin’s antibacterial effect. His observation was important, but developing a dependable medicine required further research and production work.',
      'Credit the discovery without treating it as the immediate arrival of a mass-produced drug.',
      'individuals', ['A mould inhibited the growth of nearby bacteria', 'A virus was cured by the Four Humours', 'DNA had been completely sequenced', 'Blood did not circulate around the body']),
    card(44, 'modern',
      'How did Florey, Chain and wartime production make penicillin useful?',
      'Discovery needed development, testing and supply',
      'Florey, Chain and their team developed ways to extract and test penicillin around 1940–41. Wartime support and industrial production helped supply much larger quantities. Several people and factors turned Fleming’s earlier discovery into an effective, widely available treatment.',
      'Explain how individuals, science, war, government and industry worked together.',
      'treatment'),
    card(45, 'modern',
      'What are the limits of antibiotics?',
      'They treat susceptible bacteria, not viruses',
      'Antibiotics can treat bacterial infections, but they do not cure viral illnesses such as a cold. Bacteria can evolve resistance, making a previously useful drug less effective. Antibiotics were a major advance, not a permanent answer to every infectious disease.',
      'Use resistance to qualify a judgement about how far modern medicine has progressed.',
      'treatment'),
    card(46, 'modern',
      'Why has modern surgery become more advanced?',
      'Several developments work together',
      'Safer anaesthesia, infection control, blood transfusion, imaging and specialist training allow complex operations. Examples include transplants, heart bypasses and keyhole surgery. Small incisions can reduce trauma and recovery time, but no procedure is risk-free or suitable for every patient.',
      'Explain a supporting development and its effect rather than only listing types of operation.',
      'treatment'),
    card(47, 'modern',
      'What changed when the NHS launched in 1948?',
      'Wider access to healthcare, regardless of ability to pay',
      'The NHS launched on 5 July 1948, bringing services such as GPs and hospitals into a national system intended to provide care free at the point of use. It widened access; it did not invent those treatments. Some services later had charges, so not everything has always been free.',
      'Distinguish a change in access and organisation from a new medical discovery.',
      'care', ['Access to healthcare widened through a national system launched in 1948', 'Penicillin was first discovered in 1948', 'Hospitals were invented for the first time', 'Every health problem could now be cured']),
    card(48, 'modern',
      'How do lung cancer treatment and prevention show the role of government?',
      'Treat illness and reduce risk',
      'Lung cancer treatment may include surgery, radiotherapy, chemotherapy or other specialist medicines. Tobacco controls and campaigns such as Stoptober aim to reduce smoking; campaigns such as Change4Life encouraged healthier habits more broadly. The NHS supports access to treatment, but outcomes still depend on diagnosis and the individual illness.',
      'Compare treatment with prevention, then explain how government supports each.',
      'government'),

    card(49, 'Western Front',
      'Why was moving wounded soldiers difficult on the Western Front?',
      'Mud, shell damage and enemy fire',
      'Trenches and shell holes disrupted routes, while deep mud slowed stretcher bearers and vehicles. Wounded men could remain exposed to fire, and damaged roads limited ambulances. Delays increased the danger from bleeding, shock and infection before treatment could begin.',
      'Link a physical condition to a specific problem in evacuation or treatment.',
      'care', ['Mud, shell-damaged routes and enemy fire delayed evacuation', 'Every trench had a safe railway directly to Britain', 'There were no injuries requiring transport', 'Antibiotics made delays harmless']),
    card(50, 'Western Front',
      'What caused trench foot, and how could it be prevented?',
      'Prolonged exposure to wet and cold',
      'Long periods in wet, cold conditions damaged the feet and could lead to severe injury, infection and gangrene. Keeping feet dry, changing socks, checking feet and improving drainage reduced the risk. Serious cases could require amputation.',
      'Explain why a preventive routine was easier than treating advanced damage.',
      'prevention', ['Prolonged wet and cold; prevention included dry socks and foot inspections', 'Lice bites; prevention required carbolic acid inside the lungs', 'Too much yellow bile; prevention required vaccination', 'A genetic disorder; prevention required penicillin']),
    card(51, 'Western Front',
      'How was trench fever linked to conditions in the trenches?',
      'Body lice spread the infection',
      'Body lice thrived where soldiers could not regularly wash or change clothing. They transmitted trench fever, which caused fever and pain and took men out of action. Recognising the role of lice supported delousing and cleaner clothing as preventive measures.',
      'Connect the living conditions, carrier and prevention in a clear chain.',
      'ideas', ['Body lice spread the infection in crowded, dirty conditions', 'The Four Humours were scientifically proven to cause it', 'It was caused only by exposure to chlorine gas', 'It was prevented by removing a water-pump handle']),
    card(52, 'Western Front',
      'Why was shell shock difficult for wartime doctors to deal with?',
      'Battlefield trauma was poorly understood',
      'Shell shock was a wartime term covering symptoms such as shaking, nightmares, paralysis or loss of speech. Explanations and responses varied; some soldiers received treatment while others faced stigma or accusations of cowardice. It was not simply the modern diagnosis of PTSD under a different name.',
      'Explain the medical and social difficulties without saying every sufferer was treated identically.',
      'care'),
    card(53, 'Western Front',
      'How did weapons create new problems for medical care?',
      'Severe wounds, contamination and gas injury',
      'Bullets and shell fragments damaged tissue and carried dirt into wounds, increasing infection risks. Shell blasts caused multiple injuries. Gas could damage the lungs or eyes; effects depended on the chemical. Surgeons had to manage damaged tissue, infection, bleeding and shock together.',
      'Describe a weapon’s effect and the treatment difficulty it created; avoid unsupported casualty percentages.',
      'treatment'),
    card(54, 'Western Front',
      'Why are Second Ypres and the Somme useful examples of wartime medical pressures?',
      'Gas in 1915; heavy casualties in 1916',
      'At Second Ypres in 1915, German forces used chlorine gas on a large scale, exposing troops to a new threat. The Somme in 1916 produced huge numbers of casualties, including on its first day. Both show why medical services faced unfamiliar injuries and overwhelming demand.',
      'Use the right battle and year, then explain its effect on medical care.',
      'battle context'),
    card(55, 'Western Front',
      'What do Arras, Passchendaele and Cambrai show about conditions in 1917?',
      'Different battle conditions shaped medical work',
      'Arras included underground facilities in a tunnel network. At Third Ypres, often called Passchendaele, extreme mud hampered movement and evacuation. At Cambrai, British tanks were used on a large scale and preparations included stored blood. Medical provision had to adapt to each setting.',
      'Choose the example that matches the question instead of mixing details between battles.',
      'battle context'),
    card(56, 'Western Front',
      'What was the main chain of evacuation for wounded soldiers?',
      'Aid post → dressing station → casualty clearing station → base hospital',
      'Stretcher bearers took casualties from the battlefield to a regimental aid post for immediate help. Dressing stations provided further care before transfer to a casualty clearing station for assessment and surgery when needed. Ambulance trains could take patients to base hospitals, with some later evacuated to Britain.',
      'Explain what each stage did; not every casualty passed through every stage.',
      'care', ['Aid post, dressing station, casualty clearing station, then base hospital', 'Base hospital, battlefield, then aid post', 'Pharmacy, Royal Society, then monastery', 'Casualty clearing station, battlefield, then barber-surgeon']),
    card(57, 'Western Front',
      'How did the RAMC, FANY and VADs contribute to care?',
      'Different roles supported the medical system',
      'The Royal Army Medical Corps supplied medical officers, orderlies and stretcher bearers. First Aid Nursing Yeomanry volunteers included ambulance drivers, particularly with Allied forces. Voluntary Aid Detachment members supported nursing and hospital work; they were not all professionally trained nurses.',
      'Give a distinct role for each organisation and avoid treating all volunteers as qualified doctors.',
      'care'),
    card(58, 'Western Front',
      'How did wound excision and the Thomas splint improve treatment?',
      'Remove damaged tissue and stabilise fractures',
      'Wound excision removed dead or contaminated tissue to reduce infection. The Thomas splint kept a fractured leg more stable during movement, reducing further damage and improving survival, particularly for femur fractures. Amputation was still sometimes necessary when a limb could not be saved.',
      'Link each treatment to its particular problem; splint statistics do not describe all wartime wounds.',
      'treatment', ['Excision reduced contaminated tissue; the splint stabilised leg fractures', 'Both methods cured shell shock', 'The splint was an antibiotic that killed bacteria', 'Excision prevented the need for any further surgery']),
    card(59, 'Western Front',
      'Why was Oswald Hope Robertson’s blood depot at Cambrai significant?',
      'Stored blood could be ready before casualties arrived',
      'In 1917, Robertson prepared stored blood for use around the Battle of Cambrai. Advances in preserving and storing blood reduced reliance on finding a fresh donor at the moment of treatment. Transfusion could help patients suffering from blood loss and shock.',
      'Explain how storage solved a practical limitation of transfusion near the front.',
      'treatment', ['It made preserved blood available without finding a fresh donor immediately', 'It introduced the first smallpox vaccine', 'It meant blood loss no longer happened', 'It proved that bloodletting treated every injury']),
    card(60, 'Western Front',
      'How did Cushing and Gillies respond to complex wartime injuries?',
      'Specialist brain surgery and facial reconstruction',
      'Harvey Cushing refined techniques for operating on head wounds and reducing infection. Harold Gillies developed facial reconstruction, including skin-flap techniques, and worked at the specialist hospital opened at Sidcup in 1917. Wartime injuries created urgent demand, but progress also depended on expertise and organised care.',
      'Give a specific innovation and explain why war created a need for it; do not claim war alone caused progress.',
      'individuals')
  ];
})();
