/* Official public resources; regeneration: node work/catalog-extra.cjs. */
(() => {
  const extra = {
  "checked": "2026-10-02",
  "papers": [
    {
      "id": "1MA1-1F-June-2025",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1F",
      "tier": "Foundation",
      "series": "June 2025",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1f-que-20250516.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1f-rms-20250821.pdf"
    },
    {
      "id": "1MA1-1H-June-2025",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1H",
      "tier": "Higher",
      "series": "June 2025",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1h-que-20250516.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1h-rms-20250821.pdf"
    },
    {
      "id": "1MA1-2F-June-2025",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2F",
      "tier": "Foundation",
      "series": "June 2025",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2f-que-20250605.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2f-rms-20250821.pdf"
    },
    {
      "id": "1MA1-2H-June-2025",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2H",
      "tier": "Higher",
      "series": "June 2025",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2h-que-20250605.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2h-rms-20250821.pdf"
    },
    {
      "id": "1MA1-3F-June-2025",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3F",
      "tier": "Foundation",
      "series": "June 2025",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3f-que-20250612.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3f-rms-20250821.pdf"
    },
    {
      "id": "1MA1-3H-June-2025",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3H",
      "tier": "Higher",
      "series": "June 2025",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3h-que-20250612.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3h-rms-20250821.pdf"
    },
    {
      "id": "81921-June-2025",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/1",
      "tier": "Untiered",
      "series": "June 2025",
      "paperNumber": 1,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/8cfa6a532e10bc51a7ba0fe56d5115dc918dc349.pdf",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/44b9c5a4e0d9d38854c92623ac56b0707df2737f.pdf"
    },
    {
      "id": "81922-June-2025",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/2",
      "tier": "Untiered",
      "series": "June 2025",
      "paperNumber": 2,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/48ba78cc545560a522c098fe7b3585ff7e598913.pdf",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/575964b584334b1928b5cf2df1f079a4b1c2308a.pdf"
    },
    {
      "id": "1MA1-1F-November-2024",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1F",
      "tier": "Foundation",
      "series": "November 2024",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1f-que-20241107.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1f-rms-20250109.pdf"
    },
    {
      "id": "1MA1-1H-November-2024",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1H",
      "tier": "Higher",
      "series": "November 2024",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1h-que-20241107.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1h-rms-20250109.pdf"
    },
    {
      "id": "1MA1-2F-November-2024",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2F",
      "tier": "Foundation",
      "series": "November 2024",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2f-que-20241109.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2f-rms-20250109.pdf"
    },
    {
      "id": "1MA1-2H-November-2024",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2H",
      "tier": "Higher",
      "series": "November 2024",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2h-que-20241109.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2h-rms-20250109.pdf"
    },
    {
      "id": "1MA1-3F-November-2024",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3F",
      "tier": "Foundation",
      "series": "November 2024",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3f-que-20241112.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3f-rms-20250109.pdf"
    },
    {
      "id": "1MA1-3H-November-2024",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3H",
      "tier": "Higher",
      "series": "November 2024",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3h-que-20241112.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3h-rms-20250109.pdf"
    },
    {
      "id": "1MA1-1F-June-2024",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1F",
      "tier": "Foundation",
      "series": "June 2024",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1f-que-20240517.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1f-rms-20240822.pdf"
    },
    {
      "id": "1MA1-1H-June-2024",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1H",
      "tier": "Higher",
      "series": "June 2024",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1h-que-20240517.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1h-rms-20240822.pdf"
    },
    {
      "id": "1MA1-2F-June-2024",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2F",
      "tier": "Foundation",
      "series": "June 2024",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2f-que-20240604.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2f-rms-20240822.pdf"
    },
    {
      "id": "1MA1-2H-June-2024",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2H",
      "tier": "Higher",
      "series": "June 2024",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2h-que-20240604.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2h-rms-20240822.pdf"
    },
    {
      "id": "1MA1-3F-June-2024",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3F",
      "tier": "Foundation",
      "series": "June 2024",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3f-que-20240611.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3f-rms-20240822.pdf"
    },
    {
      "id": "1MA1-3H-June-2024",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3H",
      "tier": "Higher",
      "series": "June 2024",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3h-que-20240611.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3h-rms-20240822.pdf"
    },
    {
      "id": "81921-June-2024",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/1",
      "tier": "Untiered",
      "series": "June 2024",
      "paperNumber": 1,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/68419995903e55162d8b0d278eb1b47e5a0321b2.pdf",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/b23b04838eee8faf4f746f7e8f5dbd276052f26c.pdf"
    },
    {
      "id": "81922-June-2024",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/2",
      "tier": "Untiered",
      "series": "June 2024",
      "paperNumber": 2,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/542ab3053d287d5468acf1f6b2ae807abbfb4793.pdf",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/82e58b7039fbc5085a51e1dbef124cd354c832e3.pdf"
    },
    {
      "id": "1MA1-1F-November-2023",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1F",
      "tier": "Foundation",
      "series": "November 2023",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1f-que-20231109.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1f-rms-20240111.pdf"
    },
    {
      "id": "1MA1-1H-November-2023",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1H",
      "tier": "Higher",
      "series": "November 2023",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1h-que-20231109.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1h-rms-20240111.pdf"
    },
    {
      "id": "1MA1-2F-November-2023",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2F",
      "tier": "Foundation",
      "series": "November 2023",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2f-que-20231111.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2f-rms-20240111.pdf"
    },
    {
      "id": "1MA1-2H-November-2023",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2H",
      "tier": "Higher",
      "series": "November 2023",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2h-que-20231111.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2h-rms-20240111.pdf"
    },
    {
      "id": "1MA1-3F-November-2023",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3F",
      "tier": "Foundation",
      "series": "November 2023",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3f-que-20231114.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3f-rms-20240111.pdf"
    },
    {
      "id": "1MA1-3H-November-2023",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3H",
      "tier": "Higher",
      "series": "November 2023",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3h-que-20231114.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3h-rms-20240111.pdf"
    },
    {
      "id": "1MA1-1F-June-2023",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1F",
      "tier": "Foundation",
      "series": "June 2023",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1f-que-20230520.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1f-rms-20230824.pdf"
    },
    {
      "id": "1MA1-1H-June-2023",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1H",
      "tier": "Higher",
      "series": "June 2023",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1h-que-20230520.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-1h-rms-20230824.pdf"
    },
    {
      "id": "1MA1-2F-June-2023",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2F",
      "tier": "Foundation",
      "series": "June 2023",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2f-que-20230608.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2f-rms-20230824.pdf"
    },
    {
      "id": "1MA1-2H-June-2023",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2H",
      "tier": "Higher",
      "series": "June 2023",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2h-que-20230608.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-2h-rms-20230824.pdf"
    },
    {
      "id": "1MA1-3F-June-2023",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3F",
      "tier": "Foundation",
      "series": "June 2023",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3f-que-20230615.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3f-rms-20230824.pdf"
    },
    {
      "id": "1MA1-3H-June-2023",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3H",
      "tier": "Higher",
      "series": "June 2023",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3h-que-20230615.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/Mathematics/2015/Exam-materials/1ma1-3h-rms-20230824.pdf"
    },
    {
      "id": "81921-June-2023",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/1",
      "tier": "Untiered",
      "series": "June 2023",
      "paperNumber": 1,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/98d3a7de331575b80ff0d1bd549a1598804f26dd.pdf",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/ded9980c992d117869803cc23da459c4406be4e7.pdf"
    },
    {
      "id": "81922-June-2023",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/2",
      "tier": "Untiered",
      "series": "June 2023",
      "paperNumber": 2,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/4c07879d697e15ef2c7e21531c9f30f10bd83a68.pdf",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/100ebfc15401f054255a9e1577c379913acc4f11.pdf"
    },
    {
      "id": "1MA1-1F-November-2022",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1F",
      "tier": "Foundation",
      "series": "November 2022",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-1f-que-20221102.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-1f-rms-20230112.pdf"
    },
    {
      "id": "1MA1-1H-November-2022",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1H",
      "tier": "Higher",
      "series": "November 2022",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-1h-que-20221102.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-1h-rms-20230112.pdf"
    },
    {
      "id": "1MA1-2F-November-2022",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2F",
      "tier": "Foundation",
      "series": "November 2022",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2f-que-20221104.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2f-rms-20230112.pdf"
    },
    {
      "id": "1MA1-2H-November-2022",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2H",
      "tier": "Higher",
      "series": "November 2022",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2h-que-20221104.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2h-rms-20230112.pdf"
    },
    {
      "id": "1MA1-3F-November-2022",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3F",
      "tier": "Foundation",
      "series": "November 2022",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3f-que-20221108.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3f-rms-20230112.pdf"
    },
    {
      "id": "1MA1-3H-November-2022",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3H",
      "tier": "Higher",
      "series": "November 2022",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3h-que-20221108.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3h-rms-20230112.pdf"
    },
    {
      "id": "1MA1-1F-June-2022",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1F",
      "tier": "Foundation",
      "series": "June 2022",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-1f-rms-20220825.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-1f-que-20220521.pdf"
    },
    {
      "id": "1MA1-1H-June-2022",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1H",
      "tier": "Higher",
      "series": "June 2022",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-1h-rms-20220825.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-1h-que-20220521.pdf"
    },
    {
      "id": "1MA1-2F-June-2022",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2F",
      "tier": "Foundation",
      "series": "June 2022",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2f-rms-20220825.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2f-que-20220608.pdf"
    },
    {
      "id": "1MA1-2H-June-2022",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2H",
      "tier": "Higher",
      "series": "June 2022",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2h-rms-20220825.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2h-que-20220608.pdf"
    },
    {
      "id": "1MA1-3F-June-2022",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3F",
      "tier": "Foundation",
      "series": "June 2022",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3f-rms-20220825.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3f-que-20220614.pdf"
    },
    {
      "id": "1MA1-3H-June-2022",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3H",
      "tier": "Higher",
      "series": "June 2022",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3h-rms-20220825.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3h-que-20220614.pdf"
    },
    {
      "id": "81921-June-2022",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/1",
      "tier": "Untiered",
      "series": "June 2022",
      "paperNumber": 1,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/d4f6274c1116bf48c06b13696e72dbdbb55acc45.pdf",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/b3e84363cd1327c8715fb5063a96c31edf85756b.pdf"
    },
    {
      "id": "81922-June-2022",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/2",
      "tier": "Untiered",
      "series": "June 2022",
      "paperNumber": 2,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/95626fbd5890eb1f26fb7b052afc1123c5c6bba1.pdf",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/6ca7f494814187b213f086c020df79a4f9aa93c3.pdf"
    },
    {
      "id": "1MA1-1F-November-2021",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1F",
      "tier": "Foundation",
      "series": "November 2021",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-1f-que-20211103.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-1f-rms-20220113.pdf"
    },
    {
      "id": "1MA1-1H-November-2021",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1H",
      "tier": "Higher",
      "series": "November 2021",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-1h-que-20211103.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-1h-rms-20220113.pdf"
    },
    {
      "id": "1MA1-2F-November-2021",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2F",
      "tier": "Foundation",
      "series": "November 2021",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2f-que-20211105.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2f-rms-20220113.pdf"
    },
    {
      "id": "1MA1-2H-November-2021",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2H",
      "tier": "Higher",
      "series": "November 2021",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2h-que-20211105.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2h-rms-20220113.pdf"
    },
    {
      "id": "1MA1-3F-November-2021",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3F",
      "tier": "Foundation",
      "series": "November 2021",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3f-que-20211109.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3f-rms-20220113.pdf"
    },
    {
      "id": "1MA1-3H-November-2021",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3H",
      "tier": "Higher",
      "series": "November 2021",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3h-que-20211109.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3h-rms-20220113.pdf"
    },
    {
      "id": "81921-November-2021",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/1",
      "tier": "Untiered",
      "series": "November 2021",
      "paperNumber": 1,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/83ebd9101ad6ba39d79dada5f04c1a7e2c991a51.pdf",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/d07f4ce719cc27d4319f7ba76146e4b926d567ef.pdf"
    },
    {
      "id": "81922-November-2021",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/2",
      "tier": "Untiered",
      "series": "November 2021",
      "paperNumber": 2,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/a19a65a4648c2590896107c10af7b2aeee8c8a1a.pdf",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/d445836b8de3921d631e755fecb4b9d398c50629.pdf"
    },
    {
      "id": "1MA1-1F-November-2020",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1F",
      "tier": "Foundation",
      "series": "November 2020",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_1F_msc_20210114.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-1f-que-20201104.pdf"
    },
    {
      "id": "1MA1-1H-November-2020",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1H",
      "tier": "Higher",
      "series": "November 2020",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_1H_que_20201104.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_1H_msc_20210114.pdf"
    },
    {
      "id": "1MA1-2F-November-2020",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2F",
      "tier": "Foundation",
      "series": "November 2020",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_2F_que_20201106.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_2F_msc_20210114.pdf"
    },
    {
      "id": "1MA1-2H-November-2020",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2H",
      "tier": "Higher",
      "series": "November 2020",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_2H_msc_20210114.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2h-que-20201106.pdf"
    },
    {
      "id": "1MA1-3F-November-2020",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3F",
      "tier": "Foundation",
      "series": "November 2020",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_3F_msc_20210114.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3f-que-20201110.pdf"
    },
    {
      "id": "1MA1-3H-November-2020",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3H",
      "tier": "Higher",
      "series": "November 2020",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_3H_msc_20210114.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-3h-que-20201110.pdf"
    },
    {
      "id": "81921-November-2020",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/1",
      "tier": "Untiered",
      "series": "November 2020",
      "paperNumber": 1,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/28a3a97686cff92054f141490f17056b4089b4ca.pdf",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/e2f8b533b792f2aac1f50b00baee5ec23c10abb2.pdf"
    },
    {
      "id": "81922-November-2020",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/2",
      "tier": "Untiered",
      "series": "November 2020",
      "paperNumber": 2,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/bd29931d9913778502c643842d4efff3725b92d9.pdf",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/0e237c8833f1cbb3f7af195212b16cd9c3b07fc7.pdf"
    },
    {
      "id": "1MA1-1F-November-2019",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1F",
      "tier": "Foundation",
      "series": "November 2019",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_1F_msc_20200116.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_1F_que_20200116.pdf"
    },
    {
      "id": "1MA1-1H-November-2019",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1H",
      "tier": "Higher",
      "series": "November 2019",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_1H_msc_20200116.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_1H_que_20200116.pdf"
    },
    {
      "id": "1MA1-2F-November-2019",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2F",
      "tier": "Foundation",
      "series": "November 2019",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_2F_msc_20200116.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_2F_que_20200116.pdf"
    },
    {
      "id": "1MA1-2H-November-2019",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2H",
      "tier": "Higher",
      "series": "November 2019",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_2H_msc_20200116.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_2H_que_20200116.pdf"
    },
    {
      "id": "1MA1-3F-November-2019",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3F",
      "tier": "Foundation",
      "series": "November 2019",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_3F_msc_20200116.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_3F_que_20200116.pdf"
    },
    {
      "id": "1MA1-3H-November-2019",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3H",
      "tier": "Higher",
      "series": "November 2019",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_3H_msc_20200116.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_3H_que_20200116.pdf"
    },
    {
      "id": "1MA1-1F-June-2019",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1F",
      "tier": "Foundation",
      "series": "June 2019",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_1F_rms_20190822.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_1F_que_20190522.pdf"
    },
    {
      "id": "1MA1-1H-June-2019",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/1H",
      "tier": "Higher",
      "series": "June 2019",
      "paperNumber": 1,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_1H_rms_20190822.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_1H_que_20190522.pdf"
    },
    {
      "id": "1MA1-2F-June-2019",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2F",
      "tier": "Foundation",
      "series": "June 2019",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_2F_que_20190607.pdf",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1ma1-2f-rms-20190822.pdf"
    },
    {
      "id": "1MA1-2H-June-2019",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/2H",
      "tier": "Higher",
      "series": "June 2019",
      "paperNumber": 2,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_2H_rms_20190822.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_2H_que_20190607.pdf"
    },
    {
      "id": "1MA1-3F-June-2019",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3F",
      "tier": "Foundation",
      "series": "June 2019",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_3F_rms_20190822.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_3F_que_20190612.pdf"
    },
    {
      "id": "1MA1-3H-June-2019",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1/3H",
      "tier": "Higher",
      "series": "June 2019",
      "paperNumber": 3,
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html",
      "markScheme": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_3H_rms_20190822.pdf",
      "paper": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_3H_que_20190612.pdf"
    },
    {
      "id": "81921-Sample-set-1",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/1",
      "tier": "Untiered",
      "series": "Sample set 1",
      "paperNumber": 1,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/502660dc8cd9d7f15c5e3ce8a7762b9055790845.pdf",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/85fbdb5b1341ab6c1ecd767387ce42f786c4682f.pdf"
    },
    {
      "id": "81922-Sample-set-1",
      "route": "other",
      "subject": "Sociology",
      "board": "AQA",
      "code": "8192/2",
      "tier": "Untiered",
      "series": "Sample set 1",
      "paperNumber": 2,
      "source": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources",
      "markScheme": "https://cdn.sanity.io/files/p28bar15/green/0f9cf95d833fd52fd7d68910fac90ea02b1b51b1.pdf",
      "paper": "https://cdn.sanity.io/files/p28bar15/green/7447fc7a9521228f8270639adb5cc8f2bcb9195d.pdf"
    }
  ],
  "bundles": [
    {
      "id": "1MA1-pack-November-2018",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1",
      "tier": "All tiers",
      "series": "November 2018",
      "title": "Question Papers and Mark Schemes 1MA1 November 2018",
      "url": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/question-papers-and-mark-schemes-1MA1-november-2018.zip",
      "format": "ZIP",
      "paperNumbers": [
        1,
        2,
        3
      ],
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html"
    },
    {
      "id": "1MA1-pack-June-2018",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1",
      "tier": "All tiers",
      "series": "June 2018",
      "title": "Question Papers and mark Schemes - 1MA1 - June 2018",
      "url": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/question-papers-mark-schemes-1MA1-june-2018.zip",
      "format": "ZIP",
      "paperNumbers": [
        1,
        2,
        3
      ],
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html"
    },
    {
      "id": "1MA1-pack-November-2017",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1",
      "tier": "All tiers",
      "series": "November 2017",
      "title": "Question papers and Mark schemes - 1MA1 - November 2017",
      "url": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_November_2017_QP_MS.zip",
      "format": "ZIP",
      "paperNumbers": [
        1,
        2,
        3
      ],
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html"
    },
    {
      "id": "1MA1-pack-June-2017",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1",
      "tier": "All tiers",
      "series": "June 2017",
      "title": "Question papers and Mark schemes - 1MA1 - June 2017",
      "url": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/1MA1_Summer_2017_QP_MS.zip",
      "format": "ZIP",
      "paperNumbers": [
        1,
        2,
        3
      ],
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html"
    },
    {
      "id": "1MA1-Specimen-set-2",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1",
      "tier": "All tiers",
      "series": "Specimen set 2",
      "title": "Specimen set 2 · questions and mark schemes",
      "url": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/exam-materials/GCSE-9-1-Maths-Specimen-Papers-Set-2.pdf",
      "format": "PDF",
      "paperNumbers": [
        1,
        2,
        3
      ],
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html"
    },
    {
      "id": "1MA1-Sample-assessment-materials",
      "route": "other",
      "subject": "Maths",
      "board": "Edexcel",
      "code": "1MA1",
      "tier": "All tiers",
      "series": "Sample assessment materials",
      "title": "Sample assessment materials · questions and mark schemes",
      "url": "https://qualifications.pearson.com/content/dam/pdf/GCSE/mathematics/2015/specification-and-sample-assesment/GCSE-Mathematics-2015-SAM.pdf",
      "format": "PDF",
      "paperNumbers": [
        1,
        2,
        3
      ],
      "source": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html"
    }
  ],
  "directories": [
    {
      "route": "other",
      "subject": "Edexcel Maths · Papers 1, 2 and 3",
      "code": "1MA1",
      "url": "https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.coursematerials.html"
    },
    {
      "route": "other",
      "subject": "AQA Sociology · Papers 1 and 2",
      "code": "8192",
      "url": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/assessment-resources"
    }
  ]
};
  const library = window.PAPER_LIBRARY;
  if (!library) throw new Error('Load papers-data.js before papers-extra.js');
  const existing = new Set(library.papers.map(paper => paper.id));
  library.papers.push(...extra.papers.filter(paper => !existing.has(paper.id)));
  library.bundles = extra.bundles;
  const urls = new Set(library.directories.map(directory => directory.url));
  library.directories.push(...extra.directories.filter(directory => !urls.has(directory.url)));
  library.checked = extra.checked;
})();
